/* ============================================================
   KotlinAZ — Çalışmalar bankı
   Hər mövzu üçün nəzəri (çoxvariantlı) və praktiki (kod yazma)
   çalışmalar. Praktiki çalışmaların model həlləri Kotlin
   kompilyatorunda yoxlanılır — bax: tools/verify-exercises.ps1
   ------------------------------------------------------------
   Səviyyələr: junior | middle | senior
   ============================================================ */
(function () {
  'use strict';

  var BANK = { topics: [] };
  function movzu(t) { BANK.topics.push(t); }

  /* ==========================================================
     01 · ƏSAS SİNTAKSİS
     ========================================================== */
  movzu({
    id: 'sintaksis',
    title: 'Əsas sintaksis',
    sectionId: 'sintaksis',

    nezeri: [
      { level: 'junior', q: 'Kotlin proqramı hansı funksiyadan başlayır?', opts: ['start()', 'main()', 'init()', 'run()'], a: 1, exp: 'Hər Kotlin proqramının giriş nöqtəsi main() funksiyasıdır. Java-dan fərqli olaraq o, sinif daxilində olmaq məcburiyyətində deyil — birbaşa faylda yaşaya bilər.' },
      { level: 'junior', q: 'Kotlin-də sətir sonunda nöqtəli vergül (;) qoymaq məcburidirmi?', opts: ['Bəli, həmişə', 'Xeyr, lazım deyil', 'Yalnız funksiyalarda', 'Yalnız siniflərdə'], a: 1, exp: 'Nöqtəli vergül isteğe bağlıdır. O, yalnız bir sətirdə bir neçə ifadə yazanda lazım olur — bu da tövsiyə edilmir. Yeganə məcburi hal: enum-da sabitlərdən sonra əlavə üzvlər varsa.' },
      { level: 'junior', q: 'Ekrana mətn çap etmək üçün hansı funksiya işlədilir?', opts: ['print() və println()', 'System.out.println() yalnız', 'write()', 'echo()'], a: 0, exp: 'println() mətni çap edib yeni sətrə keçir, print() isə sətri dəyişmir. Hər ikisi kotlin.io paketindədir və avtomatik import olunur.' },
      { level: 'junior', q: 'Bir sətirlik şərh necə yazılır?', opts: ['# şərh', '// şərh', '-- şərh', '<!-- şərh -->'], a: 1, exp: 'Kotlin-də bir sətirlik şərh // ilə, blok şərh isə /* ... */ ilə yazılır. Sənədləşdirmə üçün /** ... */ (KDoc) istifadə olunur.' },
      { level: 'junior', q: 'Bu kod nə çap edir?', code: 'fun main() {\n    println("Salam")\n    print("A")\n    print("B")\n}', opts: ['Salam\\nAB', 'Salam A B', 'SalamAB', 'Salam\\nA\\nB'], a: 0, exp: 'println() sonda sətir keçidi qoyur, print() isə qoymur. Ona görə "Salam" ayrıca sətirdə, "AB" isə bitişik çıxır.' },
      { level: 'junior', q: 'Paket elanı faylın harasında yazılır?', opts: ['Ən sonda', 'İstənilən yerdə', 'Ən yuxarıda, import-lardan əvvəl', 'main() daxilində'], a: 2, exp: 'package elanı faylın ilk mənalı sətri olmalıdır — yalnız şərhlər və fayl annotasiyaları ondan əvvəl gələ bilər. Ondan sonra import-lar yazılır.' },
      { level: 'junior', q: 'Kotlin-də blok şərhlər iç-içə ola bilərmi?', opts: ['Bəli', 'Xeyr', 'Yalnız KDoc-da', 'Yalnız funksiya daxilində'], a: 0, exp: 'Bəli — Kotlin-də /* /* iç-içə */ */ düzgün işləyir. Java-da bu mümkün deyil və kompilyasiya xətası verir.' },
      { level: 'junior', q: 'Aşağıdakılardan hansı düzgün funksiya elanıdır?', opts: ['function salamla() {}', 'fun salamla() {}', 'def salamla() {}', 'void salamla() {}'], a: 1, exp: 'Kotlin-də funksiya fun açar sözü ilə elan olunur. Qaytarma tipi funksiya adından və parametrlərdən sonra iki nöqtə ilə yazılır: fun ad(): Int.' },
      { level: 'junior', q: 'Mətn şablonunda dəyişəni necə yerləşdirirsən?', opts: ['"Salam {ad}"', '"Salam $ad"', '"Salam " + @ad', '"Salam %ad"'], a: 1, exp: 'Sadə dəyişən üçün $ad, ifadə üçün isə ${ad.length} forması işlədilir. Həqiqi $ simvolu lazımdırsa \\$ yazılır.' },
      { level: 'middle', q: 'Bu kodun nəticəsi nədir?', code: 'fun main() {\n    val ad = "Kotlin"\n    println("$ad dilinin adında ${ad.length} hərf var")\n}', opts: ['Kotlin dilinin adında 6 hərf var', '$ad dilinin adında ${ad.length} hərf var', 'Kotlin dilinin adında ad.length hərf var', 'Kompilyasiya xətası'], a: 0, exp: '$ad sadə dəyişəni əvəz edir, ${ad.length} isə mötərizə daxilindəki ifadəni hesablayıb nəticəsini qoyur. "Kotlin" sözündə 6 hərf var.' },
      { level: 'middle', q: 'Kotlin-də if nədir?', opts: ['Yalnız ifadədir (expression)', 'Yalnız operatordur (statement)', 'Həm operator, həm də dəyər qaytaran ifadədir', 'Java-dakı kimi yalnız operatordur'], a: 2, exp: 'Kotlin-də if dəyər qaytarır: val maks = if (a > b) a else b. Məhz buna görə dildə üçlük operator (?:) yoxdur — ehtiyac qalmır.' },
      { level: 'middle', q: 'İfadə kimi işlədilən if-də else budağı məcburidirmi?', opts: ['Xeyr, isteğe bağlıdır', 'Bəli, məcburidir', 'Yalnız Boolean qaytaranda', 'Yalnız when daxilində'], a: 1, exp: 'İfadə həmişə dəyər qaytarmalıdır. else olmasaydı, şərt yalan olanda hansı dəyər qayıdacağı bilinməzdi — ona görə kompilyator else tələb edir.' },
      { level: 'middle', q: 'Bu kod nə çap edir?', code: 'fun main() {\n    val yas = 20\n    val netice = if (yas >= 18) "boyuk" else "kicik"\n    println(netice)\n}', opts: ['boyuk', 'kicik', 'true', 'Kompilyasiya xətası'], a: 0, exp: 'if ifadə kimi işlədilib: şərt doğru olduğu üçün "boyuk" dəyəri netice dəyişəninə mənimsədilir.' },
      { level: 'middle', q: 'Hansı paketlər hər Kotlin faylına avtomatik import olunur?', opts: ['Heç biri', 'kotlin.*, kotlin.collections.*, kotlin.io.* və s.', 'Yalnız java.util.*', 'Yalnız kotlin.math.*'], a: 1, exp: 'kotlin.*, kotlin.collections.*, kotlin.io.*, kotlin.text.*, kotlin.ranges.* və JVM üçün java.lang.* avtomatik daxil edilir. println, listOf, String — hamısı buradandır.' },
      { level: 'middle', q: 'import kotlin.math.max as boyuk sətri nə edir?', opts: ['max funksiyasını silir', 'max funksiyasına boyuk adı ilə müraciət etməyə imkan verir', 'Yeni funksiya yaradır', 'Xətadır — as işlətmək olmaz'], a: 1, exp: 'as açar sözü import üçün alias (ad dəyişdirmə) yaradır. Bu, iki fərqli paketdən eyni adlı elementlər gələndə xüsusilə faydalıdır.' },
      { level: 'middle', q: 'Tək ifadəli funksiyada qaytarma tipini yazmaq məcburidirmi?', code: 'fun kvadrat(x: Int) = x * x', opts: ['Bəli, həmişə', 'Xeyr, kompilyator özü çıxarır', 'Yalnız Int üçün', 'Yalnız public funksiyalarda'], a: 1, exp: 'Tək ifadəli (= ilə yazılan) funksiyada tip çıxarışı işləyir. Amma public API-də tipi açıq yazmaq tövsiyə olunur — oxunaqlığı artırır və təsadüfi dəyişikliyin qarşısını alır.' },
      { level: 'middle', q: 'Bu kod kompilyasiya olunurmu?', code: 'fun main() {\n    val netice = try {\n        "42".toInt()\n    } catch (e: NumberFormatException) {\n        0\n    }\n    println(netice)\n}', opts: ['Bəli, 42 çap edir', 'Xeyr, try ifadə ola bilməz', 'Bəli, amma 0 çap edir', 'Xeyr, catch-də return lazımdır'], a: 0, exp: 'Kotlin-də try da ifadədir və dəyər qaytarır. "42".toInt() uğurlu olduğu üçün try blokunun son ifadəsi — yəni 42 — qaytarılır.' },
      { level: 'middle', q: 'Sinif adları üçün hansı adlandırma üslubu tövsiyə olunur?', opts: ['camelCase', 'PascalCase', 'snake_case', 'SCREAMING_SNAKE_CASE'], a: 1, exp: 'Siniflər və interfeyslər PascalCase (IstifadeciProfili), funksiya və dəyişənlər camelCase (hesablaCemi), top-level const-lar isə SCREAMING_SNAKE_CASE (MAX_OLCU) yazılır.' },
      { level: 'middle', q: 'Bu iki funksiya eyni işi görürmü?', code: 'fun a(x: Int): Int { return x + 1 }\nfun b(x: Int) = x + 1', opts: ['Bəli, tamamilə eynidir', 'Xeyr, b() dəyər qaytarmır', 'Xeyr, b() Unit qaytarır', 'Xeyr, a() daha sürətlidir'], a: 0, exp: 'Tək ifadəli forma sadəcə qısa yazılışdır. Kompilyator hər ikisi üçün eyni bayt-kodu yaradır; b()-nin qaytarma tipi Int kimi çıxarılır.' },
      { level: 'senior', q: 'main(args: Array<String>) formasında args nəyi ifadə edir?', opts: ['Mühit dəyişənlərini', 'Komanda sətri arqumentlərini', 'Sistem konfiqurasiyasını', 'Faylın yolunu'], a: 1, exp: 'args proqram işə salınarkən ötürülən komanda sətri arqumentlərini saxlayır. Arqument lazım deyilsə parametrsiz main() yazmaq kifayətdir.' },
      { level: 'senior', q: 'Enum-da nöqtəli vergül nə vaxt məcburidir?', code: 'enum class Reng(val kod: String) {\n    QIRMIZI("#F00"), YASIL("#0F0");\n\n    fun cap() = println(kod)\n}', opts: ['Heç vaxt', 'Sabitlərdən sonra əlavə üzvlər (funksiya, xassə) varsa', 'Həmişə', 'Yalnız konstruktor olanda'], a: 1, exp: 'Sabitlərin siyahısı ilə sinif gövdəsinin qalan hissəsini ayırmaq üçün nöqtəli vergül lazımdır. Yalnız sabitlər varsa o, tələb olunmur.' },
      { level: 'senior', q: 'Test funksiyalarının adında boşluq işlətmək üçün nə edilir?', opts: ['Alt xətt qoyulur', 'Backtick (`) daxilinə alınır', 'Dırnaq içinə alınır', 'Mümkün deyil'], a: 1, exp: 'Backtick daxilində Kotlin adları boşluq və xüsusi simvollar saxlaya bilər: fun `bos siyahi 0 qaytarir`() { }. Bu, testləri cümlə kimi oxunaqlı edir və əsasən test kodunda işlədilir.' },
      { level: 'senior', q: 'Faylın Java tərəfdə görünən sinif adını dəyişmək üçün hansı annotasiya işlədilir?', opts: ['@JvmStatic', '@JvmName', '@JvmField', '@JvmOverloads'], a: 1, exp: '@file:JvmName("Komekciler") faylın ən yuxarısında yazılır və Java-dan görünən adı KomekcilerKt əvəzinə Komekciler edir.' },
      { level: 'senior', q: 'Bu kodda neçə sətir çap olunur?', code: 'fun main() {\n    val gun = 6\n    val tip = when (gun) {\n        in 1..5 -> "is gunu"\n        6, 7 -> "istirahet"\n        else -> "yanlis"\n    }\n    println(tip)\n}', opts: ['0', '1', '2', '3'], a: 1, exp: 'when ifadə kimi işlədilib — o, yalnız uyğun budağın dəyərini qaytarır, heç nə çap etmir. Çap yalnız bir dəfə, sonuncu println() ilə baş verir.' },
      { level: 'senior', q: 'Kotlin faylında top-level (sinif xaricində) funksiya elan etmək mümkündürmü?', opts: ['Xeyr, hər şey sinifdə olmalıdır', 'Bəli, funksiyalar birbaşa faylda yaşaya bilər', 'Yalnız main() üçün', 'Yalnız private olanda'], a: 1, exp: 'Bu, Kotlin-in Java-dan mühüm fərqidir. Funksiya və xassələr birbaşa faylda elan oluna bilər; JVM-də onlar FaylAdiKt sinfinin statik üzvlərinə çevrilir.' }
    ],

    praktiki: [
      { level: 'junior', tapsiriq: 'Ekrana "Salam, Kotlin!" mətnini çap et.', starter: 'fun main() {\n    // Kodu bura yaz\n}', gozlenilen: 'Salam, Kotlin!', ipucu: 'println() funksiyasından istifadə et.', hell: 'fun main() {\n    println("Salam, Kotlin!")\n}' },
      { level: 'junior', tapsiriq: 'İki sətir çap et: birinci sətirdə "Birinci", ikinci sətirdə "Ikinci".', starter: 'fun main() {\n    \n}', gozlenilen: 'Birinci\nIkinci', ipucu: 'İki dəfə println() çağır.', hell: 'fun main() {\n    println("Birinci")\n    println("Ikinci")\n}' },
      { level: 'junior', tapsiriq: 'ad dəyişənini yarat və "Salam, Aysel!" çap et — adı mətn şablonu ilə yerləşdir.', starter: 'fun main() {\n    val ad = "Aysel"\n    // Sablon isledib cap et\n}', gozlenilen: 'Salam, Aysel!', ipucu: 'Dırnaq içində $ad yaz.', hell: 'fun main() {\n    val ad = "Aysel"\n    println("Salam, $ad!")\n}' },
      { level: 'junior', tapsiriq: '5 və 3 rəqəmlərinin cəmini çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '8', ipucu: 'println(5 + 3) yaz.', hell: 'fun main() {\n    println(5 + 3)\n}' },
      { level: 'junior', tapsiriq: 'print() işlədərək "A", "B", "C" hərflərini bitişik çap et, sonra sətri bitir.', starter: 'fun main() {\n    \n}', gozlenilen: 'ABC', ipucu: 'Üç dəfə print(), sonra println() çağır.', hell: 'fun main() {\n    print("A")\n    print("B")\n    print("C")\n    println()\n}' },
      { level: 'junior', tapsiriq: 'salamla adlı funksiya yaz — heç nə qaytarmasın, sadəcə "Xos geldin" çap etsin. main()-dən çağır.', starter: 'fun main() {\n    salamla()\n}\n\n// Funksiyani bura yaz', gozlenilen: 'Xos geldin', ipucu: 'fun salamla() { println("Xos geldin") }', hell: 'fun main() {\n    salamla()\n}\n\nfun salamla() {\n    println("Xos geldin")\n}' },
      { level: 'junior', tapsiriq: 'İki ədədi toplayıb qaytaran topla funksiyası yaz və 7 ilə 8-in cəmini çap et.', starter: 'fun main() {\n    println(topla(7, 8))\n}\n\n// topla funksiyasini yaz', gozlenilen: '15', ipucu: 'fun topla(a: Int, b: Int): Int { return a + b }', hell: 'fun main() {\n    println(topla(7, 8))\n}\n\nfun topla(a: Int, b: Int): Int {\n    return a + b\n}' },
      { level: 'junior', tapsiriq: 'Ədədin kvadratını qaytaran kvadrat funksiyasını TƏK İFADƏLİ formada yaz və 9-un kvadratını çap et.', starter: 'fun main() {\n    println(kvadrat(9))\n}\n\n// Tek ifadeli funksiya yaz (= isaresi ile)', gozlenilen: '81', ipucu: 'fun kvadrat(x: Int) = x * x', hell: 'fun main() {\n    println(kvadrat(9))\n}\n\nfun kvadrat(x: Int) = x * x' },
      { level: 'junior', tapsiriq: 'Bir sətirlik və blok şərh yaz, sonra "Serhler oyrenildi" çap et. Şərhlər nəticəyə təsir etməməlidir.', starter: 'fun main() {\n    \n}', gozlenilen: 'Serhler oyrenildi', ipucu: '// və /* */ işlət, sonra println() çağır.', hell: 'fun main() {\n    // Bu bir setirlik serhdir\n    /* Bu\n       blok serhdir */\n    println("Serhler oyrenildi")\n}' },
      { level: 'middle', tapsiriq: 'yas dəyişəni 20-dir. if-i İFADƏ kimi işlədib "boyuk" və ya "kicik" nəticəsini status dəyişəninə yaz və çap et.', starter: 'fun main() {\n    val yas = 20\n    val status = // buranı tamamla\n    println(status)\n}', gozlenilen: 'boyuk', ipucu: 'val status = if (yas >= 18) "boyuk" else "kicik"', hell: 'fun main() {\n    val yas = 20\n    val status = if (yas >= 18) "boyuk" else "kicik"\n    println(status)\n}' },
      { level: 'middle', tapsiriq: 'İki ədəddən böyüyünü qaytaran boyuk funksiyasını if ifadəsi ilə yaz. 14 və 27 üçün nəticəni çap et.', starter: 'fun main() {\n    println(boyuk(14, 27))\n}\n\n// boyuk funksiyasini yaz', gozlenilen: '27', ipucu: 'fun boyuk(a: Int, b: Int) = if (a > b) a else b', hell: 'fun main() {\n    println(boyuk(14, 27))\n}\n\nfun boyuk(a: Int, b: Int) = if (a > b) a else b' },
      { level: 'middle', tapsiriq: 'ad və yas dəyişənlərindən istifadə edib "Aysel 24 yasindadir" mətnini bir println() ilə çap et.', starter: 'fun main() {\n    val ad = "Aysel"\n    val yas = 24\n    \n}', gozlenilen: 'Aysel 24 yasindadir', ipucu: 'println("$ad $yas yasindadir")', hell: 'fun main() {\n    val ad = "Aysel"\n    val yas = 24\n    println("$ad $yas yasindadir")\n}' },
      { level: 'middle', tapsiriq: 'Mətn şablonunda İFADƏ işlət: "Kotlin sozunde 6 herf var" çap et. Rəqəmi əl ilə yazma — length işlət.', starter: 'fun main() {\n    val soz = "Kotlin"\n    \n}', gozlenilen: 'Kotlin sozunde 6 herf var', ipucu: '${soz.length} formasından istifadə et.', hell: 'fun main() {\n    val soz = "Kotlin"\n    println("$soz sozunde ${soz.length} herf var")\n}' },
      { level: 'middle', tapsiriq: 'when ifadəsi ilə gun = 3 üçün "Is gunu" nəticəsini hesablayıb çap et. 1..5 iş günü, 6 və 7 istirahətdir.', starter: 'fun main() {\n    val gun = 3\n    val tip = // buranı tamamla\n    println(tip)\n}', gozlenilen: 'Is gunu', ipucu: 'when (gun) { in 1..5 -> "Is gunu"; 6, 7 -> "Istirahet"; else -> "Yanlis" }', hell: 'fun main() {\n    val gun = 3\n    val tip = when (gun) {\n        in 1..5 -> "Is gunu"\n        6, 7 -> "Istirahet"\n        else -> "Yanlis"\n    }\n    println(tip)\n}' },
      { level: 'middle', tapsiriq: 'kotlin.math paketindən abs funksiyasını import edib -15 ədədinin mütləq qiymətini çap et.', starter: '// Import-u bura yaz\n\nfun main() {\n    \n}', gozlenilen: '15', ipucu: 'import kotlin.math.abs — sonra println(abs(-15)).', hell: 'import kotlin.math.abs\n\nfun main() {\n    println(abs(-15))\n}' },
      { level: 'middle', tapsiriq: 'try ifadəsindən istifadə edib "abc" mətnini rəqəmə çevirməyə çalış. Alınmasa 0 qaytarsın və nəticəni çap et.', starter: 'fun main() {\n    val netice = // try ifadesini bura yaz\n    println(netice)\n}', gozlenilen: '0', ipucu: 'try { "abc".toInt() } catch (e: NumberFormatException) { 0 }', hell: 'fun main() {\n    val netice = try {\n        "abc".toInt()\n    } catch (e: NumberFormatException) {\n        0\n    }\n    println(netice)\n}' },
      { level: 'middle', tapsiriq: 'Defolt parametrli salamla funksiyası yaz: arqument verilməsə "Dunya" işlətsin. Həm arqumentsiz, həm də "Kotlin" ilə çağır.', starter: 'fun main() {\n    salamla()\n    salamla("Kotlin")\n}\n\n// Defolt parametrli funksiya yaz', gozlenilen: 'Salam, Dunya!\nSalam, Kotlin!', ipucu: 'fun salamla(ad: String = "Dunya") { ... }', hell: 'fun main() {\n    salamla()\n    salamla("Kotlin")\n}\n\nfun salamla(ad: String = "Dunya") {\n    println("Salam, $ad!")\n}' },
      { level: 'middle', tapsiriq: 'Adlandırılmış arqumentlə çağır: melumat(ad = "Aysel", yas = 24) formasını işlət.', starter: 'fun melumat(ad: String, yas: Int) {\n    println("$ad - $yas")\n}\n\nfun main() {\n    // Adlandirilmis arqumentlerle cagir\n}', gozlenilen: 'Aysel - 24', ipucu: 'melumat(ad = "Aysel", yas = 24)', hell: 'fun melumat(ad: String, yas: Int) {\n    println("$ad - $yas")\n}\n\nfun main() {\n    melumat(ad = "Aysel", yas = 24)\n}' },
      { level: 'middle', tapsiriq: 'Həqiqi dollar işarəsi çap et: "Qiymet: $100" mətnini göstər.', starter: 'fun main() {\n    \n}', gozlenilen: 'Qiymet: $100', ipucu: 'Dollar işarəsindən əvvəl tərs xətt qoy: \\$', hell: 'fun main() {\n    println("Qiymet: \\$100")\n}' },
      { level: 'senior', tapsiriq: 'Çox sətirli mətn (üç dırnaq) işlədib iki sətir çap et: "Birinci setir" və "Ikinci setir". trimIndent() işlət.', starter: 'fun main() {\n    val metn = // uc dirnaqli metn yaz\n    println(metn)\n}', gozlenilen: 'Birinci setir\nIkinci setir', ipucu: 'Üç dırnaq açıb sətirləri yaz, sonuna .trimIndent() əlavə et.', hell: 'fun main() {\n    val metn = """\n        Birinci setir\n        Ikinci setir\n    """.trimIndent()\n    println(metn)\n}' },
      { level: 'senior', tapsiriq: 'main() funksiyasını komanda sətri arqumentləri qəbul edən formada yaz və arqumentlərin sayını çap et (arqumentsiz işlədiləcək).', starter: '// main funksiyasini args parametri ile yaz', gozlenilen: '0', ipucu: 'fun main(args: Array<String>) { println(args.size) }', hell: 'fun main(args: Array<String>) {\n    println(args.size)\n}' },
      { level: 'senior', tapsiriq: 'when-i arqumentsiz formada işlət: temperatur = 25 üçün 21-dən yuxarıdırsa "Isti", 11..20 arası "Ilig", yoxsa "Soyuq" çap et.', starter: 'fun main() {\n    val temperatur = 25\n    val netice = when {\n        // budaqlari yaz\n    }\n    println(netice)\n}', gozlenilen: 'Isti', ipucu: 'when { temperatur > 20 -> "Isti"; temperatur in 11..20 -> "Ilig"; else -> "Soyuq" }', hell: 'fun main() {\n    val temperatur = 25\n    val netice = when {\n        temperatur > 20 -> "Isti"\n        temperatur in 11..20 -> "Ilig"\n        else -> "Soyuq"\n    }\n    println(netice)\n}' },
      { level: 'senior', tapsiriq: 'Yerli (local) funksiya yaz: main() daxilində ikiqat adlı funksiya elan et və 21-in iki mislini çap et.', starter: 'fun main() {\n    // yerli funksiyani bura yaz\n    println(ikiqat(21))\n}', gozlenilen: '42', ipucu: 'main() daxilində fun ikiqat(x: Int) = x * 2 yaz.', hell: 'fun main() {\n    fun ikiqat(x: Int) = x * 2\n    println(ikiqat(21))\n}' },
      { level: 'senior', tapsiriq: 'Backtick daxilində boşluqlu adı olan funksiya elan et — adı `salam de` olsun — və onu çağır.', starter: 'fun main() {\n    // funksiyani cagir\n}\n\n// backtick daxilinde funksiya elan et', gozlenilen: 'Salam!', ipucu: 'fun `salam de`() { println("Salam!") } — çağırış da backtick ilə.', hell: 'fun main() {\n    `salam de`()\n}\n\nfun `salam de`() {\n    println("Salam!")\n}' },
      { level: 'senior', tapsiriq: 'vararg işlədib istənilən sayda ədədi toplayan cemle funksiyası yaz. 1, 2, 3, 4 üçün cəmi çap et.', starter: 'fun main() {\n    println(cemle(1, 2, 3, 4))\n}\n\n// vararg parametrli funksiya yaz', gozlenilen: '10', ipucu: 'fun cemle(vararg r: Int): Int = r.sum()', hell: 'fun main() {\n    println(cemle(1, 2, 3, 4))\n}\n\nfun cemle(vararg r: Int): Int = r.sum()' }
    ]
  });

  /* [[NOVBETI-MOVZU-BURA]] */

  window.KExercises = BANK;
})();
