/* ============================================================
   KotlinAZ — Çalışmalar bankı
   Hər mövzu üçün nəzəri (çoxvariantlı) və praktiki (kod yazma)
   çalışmalar. Praktiki çalışmaların model həlləri Kotlin
   kompilyatorunda yoxlanılır — bax: tools/verify-exercises.ps1
   ------------------------------------------------------------
   Səviyyələr: junior | middle | senior
   ============================================================ */
(function () {
  'use strict';

  var BANK = { topics: [] };
  function movzu(t) { BANK.topics.push(t); }

  /* ==========================================================
     01 · ƏSAS SİNTAKSİS
     ========================================================== */
  movzu({
    id: 'sintaksis',
    title: 'Əsas sintaksis',
    sectionId: 'sintaksis',

    nezeri: [
      { level: 'junior', q: 'Kotlin proqramı hansı funksiyadan başlayır?', opts: ['start()', 'main()', 'init()', 'run()'], a: 1, exp: 'Hər Kotlin proqramının giriş nöqtəsi main() funksiyasıdır. Java-dan fərqli olaraq o, sinif daxilində olmaq məcburiyyətində deyil — birbaşa faylda yaşaya bilər.' },
      { level: 'junior', q: 'Kotlin-də sətir sonunda nöqtəli vergül (;) qoymaq məcburidirmi?', opts: ['Bəli, həmişə', 'Xeyr, lazım deyil', 'Yalnız funksiyalarda', 'Yalnız siniflərdə'], a: 1, exp: 'Nöqtəli vergül isteğe bağlıdır. O, yalnız bir sətirdə bir neçə ifadə yazanda lazım olur — bu da tövsiyə edilmir. Yeganə məcburi hal: enum-da sabitlərdən sonra əlavə üzvlər varsa.' },
      { level: 'junior', q: 'Ekrana mətn çap etmək üçün hansı funksiya işlədilir?', opts: ['print() və println()', 'System.out.println() yalnız', 'write()', 'echo()'], a: 0, exp: 'println() mətni çap edib yeni sətrə keçir, print() isə sətri dəyişmir. Hər ikisi kotlin.io paketindədir və avtomatik import olunur.' },
      { level: 'junior', q: 'Bir sətirlik şərh necə yazılır?', opts: ['# şərh', '// şərh', '-- şərh', '<!-- şərh -->'], a: 1, exp: 'Kotlin-də bir sətirlik şərh // ilə, blok şərh isə /* ... */ ilə yazılır. Sənədləşdirmə üçün /** ... */ (KDoc) istifadə olunur.' },
      { level: 'junior', q: 'Bu kod nə çap edir?', code: 'fun main() {\n    println("Salam")\n    print("A")\n    print("B")\n}', opts: ['Salam\\nAB', 'Salam A B', 'SalamAB', 'Salam\\nA\\nB'], a: 0, exp: 'println() sonda sətir keçidi qoyur, print() isə qoymur. Ona görə "Salam" ayrıca sətirdə, "AB" isə bitişik çıxır.' },
      { level: 'junior', q: 'Paket elanı faylın harasında yazılır?', opts: ['Ən sonda', 'İstənilən yerdə', 'Ən yuxarıda, import-lardan əvvəl', 'main() daxilində'], a: 2, exp: 'package elanı faylın ilk mənalı sətri olmalıdır — yalnız şərhlər və fayl annotasiyaları ondan əvvəl gələ bilər. Ondan sonra import-lar yazılır.' },
      { level: 'junior', q: 'Kotlin-də blok şərhlər iç-içə ola bilərmi?', opts: ['Bəli', 'Xeyr', 'Yalnız KDoc-da', 'Yalnız funksiya daxilində'], a: 0, exp: 'Bəli — Kotlin-də /* /* iç-içə */ */ düzgün işləyir. Java-da bu mümkün deyil və kompilyasiya xətası verir.' },
      { level: 'junior', q: 'Aşağıdakılardan hansı düzgün funksiya elanıdır?', opts: ['function salamla() {}', 'fun salamla() {}', 'def salamla() {}', 'void salamla() {}'], a: 1, exp: 'Kotlin-də funksiya fun açar sözü ilə elan olunur. Qaytarma tipi funksiya adından və parametrlərdən sonra iki nöqtə ilə yazılır: fun ad(): Int.' },
      { level: 'junior', q: 'Mətn şablonunda dəyişəni necə yerləşdirirsən?', opts: ['"Salam {ad}"', '"Salam $ad"', '"Salam " + @ad', '"Salam %ad"'], a: 1, exp: 'Sadə dəyişən üçün $ad, ifadə üçün isə ${ad.length} forması işlədilir. Həqiqi $ simvolu lazımdırsa \\$ yazılır.' },
      { level: 'middle', q: 'Bu kodun nəticəsi nədir?', code: 'fun main() {\n    val ad = "Kotlin"\n    println("$ad dilinin adında ${ad.length} hərf var")\n}', opts: ['Kotlin dilinin adında 6 hərf var', '$ad dilinin adında ${ad.length} hərf var', 'Kotlin dilinin adında ad.length hərf var', 'Kompilyasiya xətası'], a: 0, exp: '$ad sadə dəyişəni əvəz edir, ${ad.length} isə mötərizə daxilindəki ifadəni hesablayıb nəticəsini qoyur. "Kotlin" sözündə 6 hərf var.' },
      { level: 'middle', q: 'Kotlin-də if nədir?', opts: ['Yalnız ifadədir (expression)', 'Yalnız operatordur (statement)', 'Həm operator, həm də dəyər qaytaran ifadədir', 'Java-dakı kimi yalnız operatordur'], a: 2, exp: 'Kotlin-də if dəyər qaytarır: val maks = if (a > b) a else b. Məhz buna görə dildə üçlük operator (?:) yoxdur — ehtiyac qalmır.' },
      { level: 'middle', q: 'İfadə kimi işlədilən if-də else budağı məcburidirmi?', opts: ['Xeyr, isteğe bağlıdır', 'Bəli, məcburidir', 'Yalnız Boolean qaytaranda', 'Yalnız when daxilində'], a: 1, exp: 'İfadə həmişə dəyər qaytarmalıdır. else olmasaydı, şərt yalan olanda hansı dəyər qayıdacağı bilinməzdi — ona görə kompilyator else tələb edir.' },
      { level: 'middle', q: 'Bu kod nə çap edir?', code: 'fun main() {\n    val yas = 20\n    val netice = if (yas >= 18) "boyuk" else "kicik"\n    println(netice)\n}', opts: ['boyuk', 'kicik', 'true', 'Kompilyasiya xətası'], a: 0, exp: 'if ifadə kimi işlədilib: şərt doğru olduğu üçün "boyuk" dəyəri netice dəyişəninə mənimsədilir.' },
      { level: 'middle', q: 'Hansı paketlər hər Kotlin faylına avtomatik import olunur?', opts: ['Heç biri', 'kotlin.*, kotlin.collections.*, kotlin.io.* və s.', 'Yalnız java.util.*', 'Yalnız kotlin.math.*'], a: 1, exp: 'kotlin.*, kotlin.collections.*, kotlin.io.*, kotlin.text.*, kotlin.ranges.* və JVM üçün java.lang.* avtomatik daxil edilir. println, listOf, String — hamısı buradandır.' },
      { level: 'middle', q: 'import kotlin.math.max as boyuk sətri nə edir?', opts: ['max funksiyasını silir', 'max funksiyasına boyuk adı ilə müraciət etməyə imkan verir', 'Yeni funksiya yaradır', 'Xətadır — as işlətmək olmaz'], a: 1, exp: 'as açar sözü import üçün alias (ad dəyişdirmə) yaradır. Bu, iki fərqli paketdən eyni adlı elementlər gələndə xüsusilə faydalıdır.' },
      { level: 'middle', q: 'Tək ifadəli funksiyada qaytarma tipini yazmaq məcburidirmi?', code: 'fun kvadrat(x: Int) = x * x', opts: ['Bəli, həmişə', 'Xeyr, kompilyator özü çıxarır', 'Yalnız Int üçün', 'Yalnız public funksiyalarda'], a: 1, exp: 'Tək ifadəli (= ilə yazılan) funksiyada tip çıxarışı işləyir. Amma public API-də tipi açıq yazmaq tövsiyə olunur — oxunaqlığı artırır və təsadüfi dəyişikliyin qarşısını alır.' },
      { level: 'middle', q: 'Bu kod kompilyasiya olunurmu?', code: 'fun main() {\n    val netice = try {\n        "42".toInt()\n    } catch (e: NumberFormatException) {\n        0\n    }\n    println(netice)\n}', opts: ['Bəli, 42 çap edir', 'Xeyr, try ifadə ola bilməz', 'Bəli, amma 0 çap edir', 'Xeyr, catch-də return lazımdır'], a: 0, exp: 'Kotlin-də try da ifadədir və dəyər qaytarır. "42".toInt() uğurlu olduğu üçün try blokunun son ifadəsi — yəni 42 — qaytarılır.' },
      { level: 'middle', q: 'Sinif adları üçün hansı adlandırma üslubu tövsiyə olunur?', opts: ['camelCase', 'PascalCase', 'snake_case', 'SCREAMING_SNAKE_CASE'], a: 1, exp: 'Siniflər və interfeyslər PascalCase (IstifadeciProfili), funksiya və dəyişənlər camelCase (hesablaCemi), top-level const-lar isə SCREAMING_SNAKE_CASE (MAX_OLCU) yazılır.' },
      { level: 'middle', q: 'Bu iki funksiya eyni işi görürmü?', code: 'fun a(x: Int): Int { return x + 1 }\nfun b(x: Int) = x + 1', opts: ['Bəli, tamamilə eynidir', 'Xeyr, b() dəyər qaytarmır', 'Xeyr, b() Unit qaytarır', 'Xeyr, a() daha sürətlidir'], a: 0, exp: 'Tək ifadəli forma sadəcə qısa yazılışdır. Kompilyator hər ikisi üçün eyni bayt-kodu yaradır; b()-nin qaytarma tipi Int kimi çıxarılır.' },
      { level: 'senior', q: 'main(args: Array<String>) formasında args nəyi ifadə edir?', opts: ['Mühit dəyişənlərini', 'Komanda sətri arqumentlərini', 'Sistem konfiqurasiyasını', 'Faylın yolunu'], a: 1, exp: 'args proqram işə salınarkən ötürülən komanda sətri arqumentlərini saxlayır. Arqument lazım deyilsə parametrsiz main() yazmaq kifayətdir.' },
      { level: 'senior', q: 'Enum-da nöqtəli vergül nə vaxt məcburidir?', code: 'enum class Reng(val kod: String) {\n    QIRMIZI("#F00"), YASIL("#0F0");\n\n    fun cap() = println(kod)\n}', opts: ['Heç vaxt', 'Sabitlərdən sonra əlavə üzvlər (funksiya, xassə) varsa', 'Həmişə', 'Yalnız konstruktor olanda'], a: 1, exp: 'Sabitlərin siyahısı ilə sinif gövdəsinin qalan hissəsini ayırmaq üçün nöqtəli vergül lazımdır. Yalnız sabitlər varsa o, tələb olunmur.' },
      { level: 'senior', q: 'Test funksiyalarının adında boşluq işlətmək üçün nə edilir?', opts: ['Alt xətt qoyulur', 'Backtick (`) daxilinə alınır', 'Dırnaq içinə alınır', 'Mümkün deyil'], a: 1, exp: 'Backtick daxilində Kotlin adları boşluq və xüsusi simvollar saxlaya bilər: fun `bos siyahi 0 qaytarir`() { }. Bu, testləri cümlə kimi oxunaqlı edir və əsasən test kodunda işlədilir.' },
      { level: 'senior', q: 'Faylın Java tərəfdə görünən sinif adını dəyişmək üçün hansı annotasiya işlədilir?', opts: ['@JvmStatic', '@JvmName', '@JvmField', '@JvmOverloads'], a: 1, exp: '@file:JvmName("Komekciler") faylın ən yuxarısında yazılır və Java-dan görünən adı KomekcilerKt əvəzinə Komekciler edir.' },
      { level: 'senior', q: 'Bu kodda neçə sətir çap olunur?', code: 'fun main() {\n    val gun = 6\n    val tip = when (gun) {\n        in 1..5 -> "is gunu"\n        6, 7 -> "istirahet"\n        else -> "yanlis"\n    }\n    println(tip)\n}', opts: ['0', '1', '2', '3'], a: 1, exp: 'when ifadə kimi işlədilib — o, yalnız uyğun budağın dəyərini qaytarır, heç nə çap etmir. Çap yalnız bir dəfə, sonuncu println() ilə baş verir.' },
      { level: 'senior', q: 'Kotlin faylında top-level (sinif xaricində) funksiya elan etmək mümkündürmü?', opts: ['Xeyr, hər şey sinifdə olmalıdır', 'Bəli, funksiyalar birbaşa faylda yaşaya bilər', 'Yalnız main() üçün', 'Yalnız private olanda'], a: 1, exp: 'Bu, Kotlin-in Java-dan mühüm fərqidir. Funksiya və xassələr birbaşa faylda elan oluna bilər; JVM-də onlar FaylAdiKt sinfinin statik üzvlərinə çevrilir.' }
    ],

    praktiki: [
      { level: 'junior', tapsiriq: 'Ekrana "Salam, Kotlin!" mətnini çap et.', starter: 'fun main() {\n    // Kodu bura yaz\n}', gozlenilen: 'Salam, Kotlin!', ipucu: 'println() funksiyasından istifadə et.', hell: 'fun main() {\n    println("Salam, Kotlin!")\n}' },
      { level: 'junior', tapsiriq: 'İki sətir çap et: birinci sətirdə "Birinci", ikinci sətirdə "Ikinci".', starter: 'fun main() {\n    \n}', gozlenilen: 'Birinci\nIkinci', ipucu: 'İki dəfə println() çağır.', hell: 'fun main() {\n    println("Birinci")\n    println("Ikinci")\n}' },
      { level: 'junior', tapsiriq: 'ad dəyişənini yarat və "Salam, Aysel!" çap et — adı mətn şablonu ilə yerləşdir.', starter: 'fun main() {\n    val ad = "Aysel"\n    // Sablon isledib cap et\n}', gozlenilen: 'Salam, Aysel!', ipucu: 'Dırnaq içində $ad yaz.', hell: 'fun main() {\n    val ad = "Aysel"\n    println("Salam, $ad!")\n}' },
      { level: 'junior', tapsiriq: '5 və 3 rəqəmlərinin cəmini çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '8', ipucu: 'println(5 + 3) yaz.', hell: 'fun main() {\n    println(5 + 3)\n}' },
      { level: 'junior', tapsiriq: 'print() işlədərək "A", "B", "C" hərflərini bitişik çap et, sonra sətri bitir.', starter: 'fun main() {\n    \n}', gozlenilen: 'ABC', ipucu: 'Üç dəfə print(), sonra println() çağır.', hell: 'fun main() {\n    print("A")\n    print("B")\n    print("C")\n    println()\n}' },
      { level: 'junior', tapsiriq: 'salamla adlı funksiya yaz — heç nə qaytarmasın, sadəcə "Xos geldin" çap etsin. main()-dən çağır.', starter: 'fun main() {\n    salamla()\n}\n\n// Funksiyani bura yaz', gozlenilen: 'Xos geldin', ipucu: 'fun salamla() { println("Xos geldin") }', hell: 'fun main() {\n    salamla()\n}\n\nfun salamla() {\n    println("Xos geldin")\n}' },
      { level: 'junior', tapsiriq: 'İki ədədi toplayıb qaytaran topla funksiyası yaz və 7 ilə 8-in cəmini çap et.', starter: 'fun main() {\n    println(topla(7, 8))\n}\n\n// topla funksiyasini yaz', gozlenilen: '15', ipucu: 'fun topla(a: Int, b: Int): Int { return a + b }', hell: 'fun main() {\n    println(topla(7, 8))\n}\n\nfun topla(a: Int, b: Int): Int {\n    return a + b\n}' },
      { level: 'junior', tapsiriq: 'Ədədin kvadratını qaytaran kvadrat funksiyasını TƏK İFADƏLİ formada yaz və 9-un kvadratını çap et.', starter: 'fun main() {\n    println(kvadrat(9))\n}\n\n// Tek ifadeli funksiya yaz (= isaresi ile)', gozlenilen: '81', ipucu: 'fun kvadrat(x: Int) = x * x', hell: 'fun main() {\n    println(kvadrat(9))\n}\n\nfun kvadrat(x: Int) = x * x' },
      { level: 'junior', tapsiriq: 'Bir sətirlik və blok şərh yaz, sonra "Serhler oyrenildi" çap et. Şərhlər nəticəyə təsir etməməlidir.', starter: 'fun main() {\n    \n}', gozlenilen: 'Serhler oyrenildi', ipucu: '// və /* */ işlət, sonra println() çağır.', hell: 'fun main() {\n    // Bu bir setirlik serhdir\n    /* Bu\n       blok serhdir */\n    println("Serhler oyrenildi")\n}' },
      { level: 'middle', tapsiriq: 'yas dəyişəni 20-dir. if-i İFADƏ kimi işlədib "boyuk" və ya "kicik" nəticəsini status dəyişəninə yaz və çap et.', starter: 'fun main() {\n    val yas = 20\n    val status = // buranı tamamla\n    println(status)\n}', gozlenilen: 'boyuk', ipucu: 'val status = if (yas >= 18) "boyuk" else "kicik"', hell: 'fun main() {\n    val yas = 20\n    val status = if (yas >= 18) "boyuk" else "kicik"\n    println(status)\n}' },
      { level: 'middle', tapsiriq: 'İki ədəddən böyüyünü qaytaran boyuk funksiyasını if ifadəsi ilə yaz. 14 və 27 üçün nəticəni çap et.', starter: 'fun main() {\n    println(boyuk(14, 27))\n}\n\n// boyuk funksiyasini yaz', gozlenilen: '27', ipucu: 'fun boyuk(a: Int, b: Int) = if (a > b) a else b', hell: 'fun main() {\n    println(boyuk(14, 27))\n}\n\nfun boyuk(a: Int, b: Int) = if (a > b) a else b' },
      { level: 'middle', tapsiriq: 'ad və yas dəyişənlərindən istifadə edib "Aysel 24 yasindadir" mətnini bir println() ilə çap et.', starter: 'fun main() {\n    val ad = "Aysel"\n    val yas = 24\n    \n}', gozlenilen: 'Aysel 24 yasindadir', ipucu: 'println("$ad $yas yasindadir")', hell: 'fun main() {\n    val ad = "Aysel"\n    val yas = 24\n    println("$ad $yas yasindadir")\n}' },
      { level: 'middle', tapsiriq: 'Mətn şablonunda İFADƏ işlət: "Kotlin sozunde 6 herf var" çap et. Rəqəmi əl ilə yazma — length işlət.', starter: 'fun main() {\n    val soz = "Kotlin"\n    \n}', gozlenilen: 'Kotlin sozunde 6 herf var', ipucu: '${soz.length} formasından istifadə et.', hell: 'fun main() {\n    val soz = "Kotlin"\n    println("$soz sozunde ${soz.length} herf var")\n}' },
      { level: 'middle', tapsiriq: 'when ifadəsi ilə gun = 3 üçün "Is gunu" nəticəsini hesablayıb çap et. 1..5 iş günü, 6 və 7 istirahətdir.', starter: 'fun main() {\n    val gun = 3\n    val tip = // buranı tamamla\n    println(tip)\n}', gozlenilen: 'Is gunu', ipucu: 'when (gun) { in 1..5 -> "Is gunu"; 6, 7 -> "Istirahet"; else -> "Yanlis" }', hell: 'fun main() {\n    val gun = 3\n    val tip = when (gun) {\n        in 1..5 -> "Is gunu"\n        6, 7 -> "Istirahet"\n        else -> "Yanlis"\n    }\n    println(tip)\n}' },
      { level: 'middle', tapsiriq: 'kotlin.math paketindən abs funksiyasını import edib -15 ədədinin mütləq qiymətini çap et.', starter: '// Import-u bura yaz\n\nfun main() {\n    \n}', gozlenilen: '15', ipucu: 'import kotlin.math.abs — sonra println(abs(-15)).', hell: 'import kotlin.math.abs\n\nfun main() {\n    println(abs(-15))\n}' },
      { level: 'middle', tapsiriq: 'try ifadəsindən istifadə edib "abc" mətnini rəqəmə çevirməyə çalış. Alınmasa 0 qaytarsın və nəticəni çap et.', starter: 'fun main() {\n    val netice = // try ifadesini bura yaz\n    println(netice)\n}', gozlenilen: '0', ipucu: 'try { "abc".toInt() } catch (e: NumberFormatException) { 0 }', hell: 'fun main() {\n    val netice = try {\n        "abc".toInt()\n    } catch (e: NumberFormatException) {\n        0\n    }\n    println(netice)\n}' },
      { level: 'middle', tapsiriq: 'Defolt parametrli salamla funksiyası yaz: arqument verilməsə "Dunya" işlətsin. Həm arqumentsiz, həm də "Kotlin" ilə çağır.', starter: 'fun main() {\n    salamla()\n    salamla("Kotlin")\n}\n\n// Defolt parametrli funksiya yaz', gozlenilen: 'Salam, Dunya!\nSalam, Kotlin!', ipucu: 'fun salamla(ad: String = "Dunya") { ... }', hell: 'fun main() {\n    salamla()\n    salamla("Kotlin")\n}\n\nfun salamla(ad: String = "Dunya") {\n    println("Salam, $ad!")\n}' },
      { level: 'middle', tapsiriq: 'Adlandırılmış arqumentlə çağır: melumat(ad = "Aysel", yas = 24) formasını işlət.', starter: 'fun melumat(ad: String, yas: Int) {\n    println("$ad - $yas")\n}\n\nfun main() {\n    // Adlandirilmis arqumentlerle cagir\n}', gozlenilen: 'Aysel - 24', ipucu: 'melumat(ad = "Aysel", yas = 24)', hell: 'fun melumat(ad: String, yas: Int) {\n    println("$ad - $yas")\n}\n\nfun main() {\n    melumat(ad = "Aysel", yas = 24)\n}' },
      { level: 'middle', tapsiriq: 'Həqiqi dollar işarəsi çap et: "Qiymet: $100" mətnini göstər.', starter: 'fun main() {\n    \n}', gozlenilen: 'Qiymet: $100', ipucu: 'Dollar işarəsindən əvvəl tərs xətt qoy: \\$', hell: 'fun main() {\n    println("Qiymet: \\$100")\n}' },
      { level: 'senior', tapsiriq: 'Çox sətirli mətn (üç dırnaq) işlədib iki sətir çap et: "Birinci setir" və "Ikinci setir". trimIndent() işlət.', starter: 'fun main() {\n    val metn = // uc dirnaqli metn yaz\n    println(metn)\n}', gozlenilen: 'Birinci setir\nIkinci setir', ipucu: 'Üç dırnaq açıb sətirləri yaz, sonuna .trimIndent() əlavə et.', hell: 'fun main() {\n    val metn = """\n        Birinci setir\n        Ikinci setir\n    """.trimIndent()\n    println(metn)\n}' },
      { level: 'senior', tapsiriq: 'main() funksiyasını komanda sətri arqumentləri qəbul edən formada yaz və arqumentlərin sayını çap et (arqumentsiz işlədiləcək).', starter: '// main funksiyasini args parametri ile yaz', gozlenilen: '0', ipucu: 'fun main(args: Array<String>) { println(args.size) }', hell: 'fun main(args: Array<String>) {\n    println(args.size)\n}' },
      { level: 'senior', tapsiriq: 'when-i arqumentsiz formada işlət: temperatur = 25 üçün 21-dən yuxarıdırsa "Isti", 11..20 arası "Ilig", yoxsa "Soyuq" çap et.', starter: 'fun main() {\n    val temperatur = 25\n    val netice = when {\n        // budaqlari yaz\n    }\n    println(netice)\n}', gozlenilen: 'Isti', ipucu: 'when { temperatur > 20 -> "Isti"; temperatur in 11..20 -> "Ilig"; else -> "Soyuq" }', hell: 'fun main() {\n    val temperatur = 25\n    val netice = when {\n        temperatur > 20 -> "Isti"\n        temperatur in 11..20 -> "Ilig"\n        else -> "Soyuq"\n    }\n    println(netice)\n}' },
      { level: 'senior', tapsiriq: 'Yerli (local) funksiya yaz: main() daxilində ikiqat adlı funksiya elan et və 21-in iki mislini çap et.', starter: 'fun main() {\n    // yerli funksiyani bura yaz\n    println(ikiqat(21))\n}', gozlenilen: '42', ipucu: 'main() daxilində fun ikiqat(x: Int) = x * 2 yaz.', hell: 'fun main() {\n    fun ikiqat(x: Int) = x * 2\n    println(ikiqat(21))\n}' },
      { level: 'senior', tapsiriq: 'Backtick daxilində boşluqlu adı olan funksiya elan et — adı `salam de` olsun — və onu çağır.', starter: 'fun main() {\n    // funksiyani cagir\n}\n\n// backtick daxilinde funksiya elan et', gozlenilen: 'Salam!', ipucu: 'fun `salam de`() { println("Salam!") } — çağırış da backtick ilə.', hell: 'fun main() {\n    `salam de`()\n}\n\nfun `salam de`() {\n    println("Salam!")\n}' },
      { level: 'senior', tapsiriq: 'vararg işlədib istənilən sayda ədədi toplayan cemle funksiyası yaz. 1, 2, 3, 4 üçün cəmi çap et.', starter: 'fun main() {\n    println(cemle(1, 2, 3, 4))\n}\n\n// vararg parametrli funksiya yaz', gozlenilen: '10', ipucu: 'fun cemle(vararg r: Int): Int = r.sum()', hell: 'fun main() {\n    println(cemle(1, 2, 3, 4))\n}\n\nfun cemle(vararg r: Int): Int = r.sum()' }
    ]
  });

  /* ==========================================================
     02 · DƏYİŞƏNLƏR VƏ TİPLƏR
     ========================================================== */
  movzu({
    id: 'deyisenler',
    title: 'Dəyişənlər və tiplər',
    sectionId: 'deyisenler',

    nezeri: [
      { level: 'junior', q: 'val və var arasındakı fərq nədir?', opts: ['val dəyişdirilə bilməz, var dəyişdirilə bilər', 'val yalnız rəqəmlər üçündür', 'Fərq yoxdur', 'var yalnız sinif daxilində işlədilir'], a: 0, exp: 'val yalnız-oxunan referansdır — bir dəfə təyin olunandan sonra yenidən mənimsədilə bilməz. var isə dəyişdirilə bilər. Həmişə val ilə başlamaq tövsiyə olunur.' },
      { level: 'junior', q: 'Tam ədədlər üçün defolt tip hansıdır?', opts: ['Long', 'Int', 'Short', 'Byte'], a: 1, exp: 'val x = 42 yazanda kompilyator Int tipini seçir (32 bit). Dəyər Int hüdudundan böyükdürsə avtomatik Long olur.' },
      { level: 'junior', q: 'Onluq ədədlər üçün defolt tip hansıdır?', opts: ['Float', 'Decimal', 'Double', 'Number'], a: 2, exp: 'val pi = 3.14 ifadəsində tip Double-dir (64 bit). Float almaq üçün f sonluğu lazımdır: 3.14f.' },
      { level: 'junior', q: 'Bu kod işləyirmi?', code: 'val ad = "Kotlin"\nad = "Java"', opts: ['Bəli', 'Xeyr — val yenidən təyin edilə bilməz', 'Bəli, amma xəbərdarlıqla', 'Yalnız main() daxilində'], a: 1, exp: 'val yalnız-oxunandır. Dəyəri dəyişmək lazımdırsa var işlədilməlidir.' },
      { level: 'junior', q: 'Char tipi hansı dırnaqla yazılır?', opts: ['İki dırnaq: "A"', 'Tək dırnaq: \'A\'', 'Backtick: `A`', 'Dırnaqsız: A'], a: 1, exp: 'Char tək dırnaqda yazılır (\'A\'), String isə iki dırnaqda ("A"). Bu, Kotlin-də fərqli tiplərdir.' },
      { level: 'junior', q: '1_000_000 yazılışında alt xətt nə edir?', opts: ['Dəyəri 1000 dəfə artırır', 'Yalnız oxunaqlıq üçündür, dəyərə təsiri yoxdur', 'Onu mətnə çevirir', 'Xətadır'], a: 1, exp: 'Alt xətt böyük rəqəmləri oxunaqlı edir. Kompilyator onu tamamilə nəzərə almır — 1_000_000 ilə 1000000 eyni dəyərdir.' },
      { level: 'junior', q: 'Boolean tipi hansı dəyərləri qəbul edir?', opts: ['0 və 1', 'true və false', 'yes və no', 'null və ya rəqəm'], a: 1, exp: 'Kotlin-də Boolean yalnız true və false qəbul edir. C dilindən fərqli olaraq rəqəm Boolean kimi işlədilə bilməz.' },
      { level: 'junior', q: 'Mətni rəqəmə çevirmək üçün hansı funksiya işlədilir?', opts: ['toNumber()', 'toInt()', 'parseInt()', 'asInt()'], a: 1, exp: '"42".toInt() mətni Int-ə çevirir. Çevirmə uğursuz olarsa NumberFormatException atılır — təhlükəsiz variant toIntOrNull()-dur.' },
      { level: 'junior', q: '0xFF literalı hansı say sistemindədir?', opts: ['Onluq', 'İkilik', 'Onaltılıq (hex)', 'Səkkizlik'], a: 2, exp: '0x prefiksi onaltılıq sistemi bildirir. 0xFF onluq sistemdə 255-ə bərabərdir. İkilik üçün 0b prefiksi işlədilir.' },
      { level: 'middle', q: 'Bu kod kompilyasiya olunurmu?', code: 'val x: Int = 10\nval y: Long = x', opts: ['Bəli', 'Xeyr — açıq çevirmə lazımdır: x.toLong()', 'Bəli, amma dəyər itir', 'Yalnız x sabit olanda'], a: 1, exp: 'Kotlin avtomatik rəqəm çevrilməsi etmir — Java-dan mühüm fərqdir. Bu, gizli məlumat itkisinin qarşısını alır. Açıq şəkildə x.toLong() yazmaq lazımdır.' },
      { level: 'middle', q: '7 / 2 ifadəsinin nəticəsi nədir?', opts: ['3.5', '3', '4', '3.0'], a: 1, exp: 'Hər iki operand Int olduğu üçün tam bölmə aparılır və kəsr hissə atılır. Onluq nəticə üçün ən azı biri Double olmalıdır: 7.0 / 2 → 3.5.' },
      { level: 'middle', q: '"abc".toIntOrNull() nə qaytarır?', opts: ['0', 'null', 'NumberFormatException atır', '-1'], a: 1, exp: 'toIntOrNull() çevirmə mümkün olmayanda istisna atmır, null qaytarır. Bu, istifadəçi girişini emal edərkən ən təhlükəsiz yanaşmadır.' },
      { level: 'middle', q: 'const val ilə adi val arasındakı fərq nədir?', opts: ['Fərq yoxdur', 'const val kompilyasiya vaxtı sabitdir və yalnız primitiv/String ola bilər', 'const val daha çox yaddaş tutur', 'const val yalnız sinif daxilində olur'], a: 1, exp: 'const val dəyəri kompilyasiya vaxtı məlum olmalıdır və yalnız top-level, object və ya companion object daxilində elan edilə bilər. Çalışma vaxtı hesablanan dəyərlər üçün adi val işlədilir.' },
      { level: 'middle', q: 'lateinit hansı tiplərlə İŞLƏMİR?', opts: ['String', 'Sinif tipləri', 'Primitiv tiplər (Int, Double, Boolean)', 'List'], a: 2, exp: 'lateinit primitiv tiplərlə işləmir, çünki onların «hələ təyin olunmayıb» vəziyyətini bildirən daxili null dəyəri yoxdur. Bunun üçün by Delegates.notNull() işlədilir.' },
      { level: 'middle', q: 'by lazy nə vaxt hesablanır?', opts: ['Proqram başlayanda', 'Hər müraciətdə yenidən', 'İlk müraciətdə bir dəfə, sonra keşlənir', 'Heç vaxt'], a: 2, exp: 'by lazy dəyəri ilk oxunuşda hesablayır və nəticəni saxlayır. Növbəti müraciətlərdə hesablama təkrarlanmır. Yalnız val ilə işlədilə bilər.' },
      { level: 'middle', q: 'Bu kodun nəticəsi nədir?', code: 'val a = "Kotlin"\nval b = StringBuilder("Kot").append("lin").toString()\nprintln(a == b)\nprintln(a === b)', opts: ['true / true', 'true / false', 'false / false', 'false / true'], a: 1, exp: '== məzmunu müqayisə edir (equals) — hər iki mətn "Kotlin" olduğu üçün true. === isə referansı yoxlayır; StringBuilder yeni obyekt yaratdığı üçün false.' },
      { level: 'middle', q: 'val siyahi = mutableListOf(1); siyahi.add(2) — bu işləyirmi?', opts: ['Xeyr, val dəyişməzdir', 'Bəli — val referansı sabitləyir, obyektin məzmununu yox', 'Yalnız var olsa', 'Kompilyasiya xətası'], a: 1, exp: 'val yalnız referansın yenidən mənimsədilməsini qadağan edir. Obyektin özü dəyişkəndirsə (MutableList), məzmunu dəyişdirilə bilər.' },
      { level: 'middle', q: '\'K\'.code ifadəsi nə qaytarır?', opts: ['\'K\' simvolunu', 'Unicode kodunu (75)', 'Mətn "K"', 'Xəta'], a: 1, exp: 'Char.code simvolun Unicode kod nöqtəsini Int kimi qaytarır. Əks çevirmə üçün 75.toChar() işlədilir.' },
      { level: 'middle', q: 'Int tipinin maksimum dəyəri nədir?', opts: ['2147483647', '65535', '9223372036854775807', '2147483648'], a: 0, exp: 'Int 32 bitdir: −2 147 483 648 … 2 147 483 647. Daha böyük dəyərlər üçün Long (64 bit) işlədilir.' },
      { level: 'senior', q: 'Int.MAX_VALUE + 1 ifadəsinin nəticəsi nədir?', opts: ['Xəta atır', 'Long-a çevrilir', 'Int.MIN_VALUE (−2147483648)', '0'], a: 2, exp: 'Kotlin-də tam ədəd daşması (overflow) səssiz baş verir — dəyər diapazonun əvvəlinə qayıdır. Xəta atılmır, ona görə böyük hesablamalarda Long işlətmək lazımdır.' },
      { level: 'senior', q: 'Kotlin-də Unit nədir?', opts: ['null-un başqa adı', 'Java-dakı void-in qarşılığı — real tipdir və bir nüsxəsi var', 'Boş siyahı', 'Xəta tipi'], a: 1, exp: 'Unit heç nə qaytarmayan funksiyaların qaytarma tipidir. void-dən fərqi: Unit real tipdir, generiklərdə istifadə oluna bilər və yalnız bir nüsxəsi mövcuddur.' },
      { level: 'senior', q: 'Nothing tipi nə vaxt işlədilir?', opts: ['Boş dəyər üçün', 'Heç vaxt qaytarmayan ifadələr üçün (throw, sonsuz dövr)', 'null üçün', 'Boolean üçün'], a: 1, exp: 'Nothing heç bir dəyəri olmayan tipdir. throw ifadəsinin tipi Nothing-dir, ona görə val x = y ?: throw Xeta() konstruksiyası işləyir — Nothing bütün tiplərin alt tipidir.' },
      { level: 'senior', q: 'Bu kodda x-in tipi nədir?', code: 'val x = 10000000000', opts: ['Int', 'Long', 'Double', 'Kompilyasiya xətası'], a: 1, exp: 'Dəyər Int hüdudundan (2 147 483 647) böyükdür, ona görə kompilyator avtomatik Long seçir. L sonluğu yazmaq məcburi deyil.' },
      { level: 'senior', q: 'Kotlin-də primitiv tiplər varmı?', opts: ['Bəli, int və Integer ayrıdır', 'Xeyr — dildə yalnız Int var, kompilyator lazım olanda onu primitivə çevirir', 'Yalnız Boolean primitivdir', 'Hamısı obyektdir və heç vaxt optimallaşdırılmır'], a: 1, exp: 'Kotlin səviyyəsində hər şey obyektdir, amma JVM-də kompilyator Int-i mümkün olan yerlərdə primitiv int kimi saxlayır. Nullable olanda (Int?) isə boxing baş verir.' },
      { level: 'senior', q: 'val x: Int? = null; val y = x?.plus(1) — y-in tipi nədir?', opts: ['Int', 'Int?', 'Nothing', 'Kompilyasiya xətası'], a: 1, exp: 'Safe call (?.) nəticəsi həmişə nullable olur, çünki receiver null olsa nəticə də null olur. Ona görə y-in tipi Int?-dir.' }
    ],

    praktiki: [
      { level: 'junior', tapsiriq: 'ad adlı dəyişməz dəyişən yarat, dəyəri "Kotlin" olsun və çap et.', starter: 'fun main() {\n    \n}', gozlenilen: 'Kotlin', ipucu: 'val açar sözündən istifadə et.', hell: 'fun main() {\n    val ad = "Kotlin"\n    println(ad)\n}' },
      { level: 'junior', tapsiriq: 'sayqac adlı dəyişkən dəyişən yarat (0-dan başlasın), üç dəfə bir vahid artır və nəticəni çap et.', starter: 'fun main() {\n    var sayqac = 0\n    \n}', gozlenilen: '3', ipucu: 'sayqac++ üç dəfə, sonra println(sayqac).', hell: 'fun main() {\n    var sayqac = 0\n    sayqac++\n    sayqac++\n    sayqac++\n    println(sayqac)\n}' },
      { level: 'junior', tapsiriq: 'Int tipli 7 və Double tipli 2.0 dəyərlərini böl və nəticəni çap et.', starter: 'fun main() {\n    val a = 7\n    val b = 2.0\n    \n}', gozlenilen: '3.5', ipucu: 'println(a / b) — biri Double olduğu üçün nəticə Double olur.', hell: 'fun main() {\n    val a = 7\n    val b = 2.0\n    println(a / b)\n}' },
      { level: 'junior', tapsiriq: 'İki Int ədədin tam bölmə nəticəsini çap et: 7 bölünsün 2-yə.', starter: 'fun main() {\n    \n}', gozlenilen: '3', ipucu: 'Hər iki operand Int olanda kəsr hissə atılır.', hell: 'fun main() {\n    println(7 / 2)\n}' },
      { level: 'junior', tapsiriq: '1_000_000 dəyərini dəyişəndə saxla və çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '1000000', ipucu: 'Alt xətt yalnız oxunaqlıq üçündür.', hell: 'fun main() {\n    val boyuk = 1_000_000\n    println(boyuk)\n}' },
      { level: 'junior', tapsiriq: 'Onaltılıq 0xFF dəyərini çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '255', ipucu: 'println(0xFF) yaz.', hell: 'fun main() {\n    println(0xFF)\n}' },
      { level: 'junior', tapsiriq: 'İkilik 0b1010 dəyərini çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '10', ipucu: '0b prefiksi ikilik say sistemi bildirir.', hell: 'fun main() {\n    println(0b1010)\n}' },
      { level: 'junior', tapsiriq: '"42" mətnini Int-ə çevirib 8 əlavə et və nəticəni çap et.', starter: 'fun main() {\n    val metn = "42"\n    \n}', gozlenilen: '50', ipucu: 'metn.toInt() + 8', hell: 'fun main() {\n    val metn = "42"\n    println(metn.toInt() + 8)\n}' },
      { level: 'junior', tapsiriq: 'Boolean dəyişən yarat (true) və onun inkarını çap et.', starter: 'fun main() {\n    val aktivdir = true\n    \n}', gozlenilen: 'false', ipucu: 'İnkar üçün ! işarəsi işlədilir.', hell: 'fun main() {\n    val aktivdir = true\n    println(!aktivdir)\n}' },
      { level: 'middle', tapsiriq: 'Int dəyəri açıq şəkildə Long-a çevirib çap et. Dəyər 42 olsun.', starter: 'fun main() {\n    val x: Int = 42\n    val y: Long = // buranı tamamla\n    println(y)\n}', gozlenilen: '42', ipucu: 'x.toLong() işlət — Kotlin avtomatik çevirmir.', hell: 'fun main() {\n    val x: Int = 42\n    val y: Long = x.toLong()\n    println(y)\n}' },
      { level: 'middle', tapsiriq: '"abc" mətnini təhlükəsiz şəkildə rəqəmə çevirməyə çalış və nəticəni çap et (istisna atılmamalıdır).', starter: 'fun main() {\n    \n}', gozlenilen: 'null', ipucu: 'toIntOrNull() istisna atmır, null qaytarır.', hell: 'fun main() {\n    println("abc".toIntOrNull())\n}' },
      { level: 'middle', tapsiriq: '\'K\' simvolunun Unicode kodunu çap et.', starter: 'fun main() {\n    val herf = \'K\'\n    \n}', gozlenilen: '75', ipucu: 'Char.code xassəsindən istifadə et.', hell: 'fun main() {\n    val herf = \'K\'\n    println(herf.code)\n}' },
      { level: 'middle', tapsiriq: '75 kodunu simvola çevirib çap et.', starter: 'fun main() {\n    \n}', gozlenilen: 'K', ipucu: 'Int.toChar() işlət.', hell: 'fun main() {\n    println(75.toChar())\n}' },
      { level: 'middle', tapsiriq: 'Int tipinin maksimum və minimum dəyərlərini iki sətirdə çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '2147483647\n-2147483648', ipucu: 'Int.MAX_VALUE və Int.MIN_VALUE.', hell: 'fun main() {\n    println(Int.MAX_VALUE)\n    println(Int.MIN_VALUE)\n}' },
      { level: 'middle', tapsiriq: 'val ilə mutableListOf(1, 2) yarat, ona 3 əlavə et və siyahını çap et. (val referansı sabitləyir, məzmunu yox.)', starter: 'fun main() {\n    val siyahi = mutableListOf(1, 2)\n    \n}', gozlenilen: '[1, 2, 3]', ipucu: 'siyahi.add(3) işləyir, çünki obyektin özü dəyişkəndir.', hell: 'fun main() {\n    val siyahi = mutableListOf(1, 2)\n    siyahi.add(3)\n    println(siyahi)\n}' },
      { level: 'middle', tapsiriq: 'İki mətni müqayisə et: biri adi literal, digəri StringBuilder ilə qurulsun. == və === nəticələrini iki sətirdə çap et.', starter: 'fun main() {\n    val a = "Kotlin"\n    val b = StringBuilder("Kot").append("lin").toString()\n    \n}', gozlenilen: 'true\nfalse', ipucu: '== məzmunu, === referansı müqayisə edir.', hell: 'fun main() {\n    val a = "Kotlin"\n    val b = StringBuilder("Kot").append("lin").toString()\n    println(a == b)\n    println(a === b)\n}' },
      { level: 'middle', tapsiriq: 'Top-level const val ilə MAX_OLCU sabiti yarat (dəyəri 100) və main() daxilində çap et.', starter: '// const val sabitini bura yaz\n\nfun main() {\n    println(MAX_OLCU)\n}', gozlenilen: '100', ipucu: 'const val MAX_OLCU = 100', hell: 'const val MAX_OLCU = 100\n\nfun main() {\n    println(MAX_OLCU)\n}' },
      { level: 'middle', tapsiriq: 'Dəyişənin tipini çap et: 3.14 dəyərinin sadə sinif adını göstər.', starter: 'fun main() {\n    val pi = 3.14\n    \n}', gozlenilen: 'Double', ipucu: 'pi::class.simpleName işlət.', hell: 'fun main() {\n    val pi = 3.14\n    println(pi::class.simpleName)\n}' },
      { level: 'middle', tapsiriq: 'Qalıq (mod) əməliyyatı ilə 17-nin 5-ə bölünməsindən qalanı çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '2', ipucu: '% operatorundan istifadə et.', hell: 'fun main() {\n    println(17 % 5)\n}' },
      { level: 'senior', tapsiriq: 'Int daşmasını göstər: Int.MAX_VALUE üzərinə 1 əlavə edib nəticəni çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '-2147483648', ipucu: 'Kotlin-də daşma səssiz baş verir — dəyər diapazonun əvvəlinə qayıdır.', hell: 'fun main() {\n    println(Int.MAX_VALUE + 1)\n}' },
      { level: 'senior', tapsiriq: 'by lazy işlədib agir adlı dəyər yarat — hesablanarkən "Hesablanir" çap etsin. Sonra ona İKİ dəfə müraciət et.', starter: 'val agir: Int by lazy {\n    // burani tamamla\n}\n\nfun main() {\n    println(agir)\n    println(agir)\n}', gozlenilen: 'Hesablanir\n42\n42', ipucu: 'Blok daxilində println("Hesablanir") yaz, sonra 42 qaytar. lazy yalnız bir dəfə hesablayır.', hell: 'val agir: Int by lazy {\n    println("Hesablanir")\n    42\n}\n\nfun main() {\n    println(agir)\n    println(agir)\n}' },
      { level: 'senior', tapsiriq: 'Nullable Int dəyişəni null olsun. Safe call ilə ona 1 əlavə etməyə çalış və nəticəni çap et.', starter: 'fun main() {\n    val x: Int? = null\n    \n}', gozlenilen: 'null', ipucu: 'x?.plus(1) yaz — receiver null olduğu üçün nəticə null olur.', hell: 'fun main() {\n    val x: Int? = null\n    println(x?.plus(1))\n}' },
      { level: 'senior', tapsiriq: 'Elvis operatoru ilə nullable dəyəri emal et: x null olduqda 0 çap olunsun.', starter: 'fun main() {\n    val x: Int? = null\n    \n}', gozlenilen: '0', ipucu: 'println(x ?: 0)', hell: 'fun main() {\n    val x: Int? = null\n    println(x ?: 0)\n}' },
      { level: 'senior', tapsiriq: 'is operatoru ilə tip yoxla: Any tipli dəyişən String saxlayırsa uzunluğunu çap et.', starter: 'fun main() {\n    val obyekt: Any = "Kotlin"\n    \n}', gozlenilen: '6', ipucu: 'if (obyekt is String) — smart cast sayəsində obyekt.length işləyir.', hell: 'fun main() {\n    val obyekt: Any = "Kotlin"\n    if (obyekt is String) {\n        println(obyekt.length)\n    }\n}' },
      { level: 'senior', tapsiriq: 'Char üzərində arifmetika: \'a\' simvoluna 1 əlavə edib nəticəni çap et.', starter: 'fun main() {\n    \n}', gozlenilen: 'b', ipucu: '\'a\' + 1 nəticəsi Char tipindədir.', hell: 'fun main() {\n    println(\'a\' + 1)\n}' }
    ]
  });

  /* ==========================================================
     03 · ŞƏRTLƏR: if VƏ when
     ========================================================== */
  movzu({
    id: 'sertler',
    title: 'Şərtlər: if və when',
    sectionId: 'sertler',

    nezeri: [
      { level: 'junior', q: 'Kotlin-də üçlük operator (şərt ? a : b) varmı?', opts: ['Bəli', 'Xeyr — if ifadəsi onu əvəz edir', 'Yalnız Boolean üçün', 'Yalnız when daxilində'], a: 1, exp: 'Kotlin-də üçlük operator yoxdur, çünki if özü dəyər qaytarır: val maks = if (a > b) a else b. Bu forma daha oxunaqlıdır.' },
      { level: 'junior', q: 'İfadə kimi işlədilən if-də else məcburidirmi?', opts: ['Xeyr', 'Bəli', 'Yalnız Int qaytaranda', 'Yalnız funksiya daxilində'], a: 1, exp: 'İfadə həmişə dəyər qaytarmalıdır. else olmasa, şərt yalan olanda hansı dəyərin qayıdacağı bilinməz — ona görə kompilyator else tələb edir.' },
      { level: 'junior', q: 'when nəyin qarşılığıdır?', opts: ['Java-dakı switch — amma daha güclüdür', 'for dövrünün', 'try blokunun', 'Funksiya elanının'], a: 0, exp: 'when switch-ə bənzəyir, amma istənilən tipi, aralıqları, tip yoxlamalarını və ixtiyari şərtləri qəbul edir. Həmçinin dəyər qaytara bilir.' },
      { level: 'junior', q: 'when-də bir neçə dəyəri eyni budağa necə yığmaq olar?', opts: ['Vergüllə: 1, 2, 3 ->', 'Nöqtəli vergüllə', '|| operatoru ilə', 'Mümkün deyil'], a: 0, exp: 'Dəyərlər vergüllə sadalanır: 1, 2, 3 -> "kiçik". Java-dakı kimi ardıcıl case yazmağa ehtiyac yoxdur.' },
      { level: 'junior', q: 'Bu kod nə çap edir?', code: 'fun main() {\n    val x = 5\n    if (x > 3) println("boyuk") else println("kicik")\n}', opts: ['boyuk', 'kicik', 'Hər ikisi', 'Heç nə'], a: 0, exp: '5 > 3 şərti doğrudur, ona görə if budağı işləyir və "boyuk" çap olunur.' },
      { level: 'junior', q: 'when-də «qalan bütün hallar» üçün hansı açar söz işlədilir?', opts: ['default', 'else', 'otherwise', 'other'], a: 1, exp: 'Kotlin-də else işlədilir. İfadə kimi işlədilən when-də o məcburidir — enum və sealed tiplərdə isə bütün hallar əhatə olunubsa lazım deyil.' },
      { level: 'junior', q: 'Bloklu if ifadəsində hansı dəyər qaytarılır?', opts: ['Birinci sətir', 'Son sətir', 'return yazılan sətir', 'Heç biri'], a: 1, exp: 'Blokun son ifadəsi nəticə olur. Ona görə if bloklarında ayrıca return yazmağa ehtiyac yoxdur.' },
      { level: 'junior', q: 'Şərtdə «və» əməliyyatı hansı operatorla yazılır?', opts: ['and', '&&', '&', 'AND'], a: 1, exp: 'Məntiqi «və» üçün && işlədilir və qısa qapanma (short-circuit) tətbiq olunur — sol tərəf false olsa sağ heç hesablanmır.' },
      { level: 'middle', q: 'Bu kodun nəticəsi nədir?', code: 'fun main() {\n    val bal = 85\n    val q = if (bal >= 90) "Ela" else if (bal >= 70) "Yaxsi" else "Kafi"\n    println(q)\n}', opts: ['Ela', 'Yaxsi', 'Kafi', 'Kompilyasiya xətası'], a: 1, exp: '85 >= 90 yalandır, 85 >= 70 doğrudur — ona görə "Yaxsi" seçilir və q dəyişəninə mənimsədilir.' },
      { level: 'middle', q: 'when-də aralıq yoxlaması necə yazılır?', opts: ['between 1 and 10 ->', 'in 1..10 ->', 'range(1,10) ->', '1 <= x <= 10 ->'], a: 1, exp: 'in açar sözü ilə: in 1..10 -> "kicik". Əksi üçün !in işlədilir.' },
      { level: 'middle', q: 'Arqumentsiz when nə vaxt faydalıdır?', opts: ['Heç vaxt', 'Bir-birindən asılı olmayan şərtləri yoxlamaq üçün — if-else zəncirini əvəz edir', 'Yalnız enum ilə', 'Yalnız null yoxlaması üçün'], a: 1, exp: 'when { a > 10 -> ...; b.isEmpty() -> ... } formasında hər budaq müstəqil Boolean şərtdir. Bu, uzun if-else if zəncirlərini daha oxunaqlı edir.' },
      { level: 'middle', q: 'when daxilində is işlədəndə smart cast baş verirmi?', code: 'when (obyekt) {\n    is String -> println(obyekt.length)\n}', opts: ['Xeyr, əl ilə çevirmək lazımdır', 'Bəli — budaq daxilində obyekt avtomatik String kimi görünür', 'Yalnız val olanda', 'Yalnız as işlədiləndə'], a: 1, exp: 'is yoxlamasından sonra kompilyator dəyişəni həmin tipdə görür. Əlavə (obyekt as String) yazmağa ehtiyac qalmır.' },
      { level: 'middle', q: 'Bu kodun nəticəsi nədir?', code: 'fun main() {\n    val gun = 6\n    val tip = when (gun) {\n        in 1..5 -> "is"\n        6, 7 -> "istirahet"\n        else -> "yanlis"\n    }\n    println(tip)\n}', opts: ['is', 'istirahet', 'yanlis', 'Kompilyasiya xətası'], a: 1, exp: '6 dəyəri birinci budağın aralığına (1..5) düşmür, ikinci budaqda isə açıq sadalanıb — ona görə "istirahet" seçilir.' },
      { level: 'middle', q: 'when (val n = hesabla()) { ... } konstruksiyası nə edir?', opts: ['Xətadır', 'Nəticəni dəyişəndə saxlayır və həmin when daxilində işlədir', 'Funksiyanı iki dəfə çağırır', 'Yalnız Java-da işləyir'], a: 1, exp: 'when-in subject-ində dəyişən elan etmək olar. Funksiya yalnız bir dəfə çağırılır və nəticə bütün budaqlarda əlçatan olur.' },
      { level: 'middle', q: 'enum ilə işlədilən when-də else nə vaxt lazım OLMUR?', opts: ['Heç vaxt lazım olmur', 'Bütün enum sabitləri əhatə olunubsa', 'Yalnız iki sabit olanda', 'Həmişə lazımdır'], a: 1, exp: 'Kompilyator enum-un bütün dəyərlərini tanıyır. Hamısı sadalanıbsa when exhaustive sayılır və else tələb olunmur.' },
      { level: 'middle', q: '&& operatorunda qısa qapanma nə deməkdir?', opts: ['Hər iki tərəf həmişə hesablanır', 'Sol tərəf false olsa sağ tərəf hesablanmır', 'Sağ tərəf əvvəl hesablanır', 'Nəticə həmişə true olur'], a: 1, exp: 'Sol tərəf nəticəni müəyyən edirsə sağ tərəf işlədilmir. Bu, siyahi != null && siyahi.isNotEmpty() kimi yoxlamaları təhlükəsiz edir.' },
      { level: 'middle', q: 'if ifadəsini funksiyadan birbaşa qaytarmaq olarmı?', code: 'fun boyuk(a: Int, b: Int) = if (a > b) a else b', opts: ['Xeyr', 'Bəli — tək ifadəli funksiya forması', 'Yalnız return ilə', 'Yalnız Unit qaytaranda'], a: 1, exp: 'if dəyər qaytardığı üçün tək ifadəli funksiyanın gövdəsi ola bilər. Bu, çox işlədilən idiomatik formadır.' },
      { level: 'senior', q: 'sealed class ilə when-in üstünlüyü nədir?', opts: ['Daha sürətli işləyir', 'Bütün varislər məlum olduğu üçün else lazım olmur və yeni varis əlavə edəndə kompilyator xəbərdarlıq verir', 'Yaddaşa qənaət edir', 'Fərq yoxdur'], a: 1, exp: 'sealed iyerarxiyanın bütün varisləri kompilyatora məlumdur. Yeni varis əlavə edəndə onu emal etməyən bütün when blokları kompilyasiya xətası verir — heç bir hal unudulmur.' },
      { level: 'senior', q: 'Bu when exhaustive-dirmi?', code: 'enum class Status { AKTIV, PASSIV }\n\nfun ad(s: Status): String = when (s) {\n    Status.AKTIV -> "aktiv"\n    Status.PASSIV -> "passiv"\n}', opts: ['Xeyr, else lazımdır', 'Bəli — bütün enum dəyərləri əhatə olunub', 'Yalnız else əlavə etsək', 'Kompilyasiya xətası verir'], a: 1, exp: 'Hər iki enum sabiti sadalanıb, ona görə when exhaustive-dir və else tələb olunmur.' },
      { level: 'senior', q: 'when-də budaqlar hansı ardıcıllıqla yoxlanılır?', opts: ['Təsadüfi', 'Yuxarıdan aşağı, ilk uyğun gələn işləyir', 'Aşağıdan yuxarı', 'Hamısı eyni anda'], a: 1, exp: 'Budaqlar yazıldığı ardıcıllıqla yoxlanılır və ilk uyğun gələn icra olunur. Ona görə daha spesifik şərtlər yuxarıda yazılmalıdır.' },
      { level: 'senior', q: 'if-in nəticəsini birbaşa string şablonuna qoymaq olarmı?', opts: ['Xeyr', 'Bəli — ${if (x > 0) "musbet" else "menfi"}', 'Yalnız dəyişən vasitəsilə', 'Yalnız when ilə'], a: 1, exp: '${...} daxilində istənilən ifadə yazıla bilər, o cümlədən if. Amma oxunaqlıq üçün mürəkkəb məntiqi ayrıca dəyişənə çıxarmaq daha yaxşıdır.' },
      { level: 'senior', q: 'Boolean dəyəri if ilə yoxlayıb true/false qaytarmaq niyə pisdir?', code: 'if (x > 5) true else false', opts: ['Pis deyil', 'Lazımsızdır — x > 5 özü onsuz da Boolean qaytarır', 'Xəta verir', 'Yavaş işləyir'], a: 1, exp: 'Müqayisə nəticəsi artıq Boolean-dır. Sadəcə x > 5 yazmaq kifayətdir — bu, ümumi kod qoxusu (code smell) sayılır.' },
      { level: 'senior', q: 'when-in bütün budaqları fərqli tip qaytarırsa nəticənin tipi nə olur?', code: 'val x = when (n) {\n    1 -> "bir"\n    2 -> 2\n    else -> null\n}', opts: ['String', 'Int', 'Ən yaxın ortaq üst tip (bu halda Any?)', 'Kompilyasiya xətası'], a: 2, exp: 'Kompilyator bütün budaqların ortaq üst tipini seçir. String, Int və null üçün bu Any?-dir. Belə hallardan qaçmaq və tipi vahid saxlamaq tövsiyə olunur.' },
      { level: 'senior', q: 'İç-içə çoxlu if əvəzinə hansı yanaşma tövsiyə olunur?', opts: ['Daha çox if yazmaq', 'Erkən çıxış (early return) və ya arqumentsiz when', 'goto işlətmək', 'Hamısını bir sətirdə yazmaq'], a: 1, exp: 'Erkən çıxış (val x = giris ?: return) və arqumentsiz when kodu düzləşdirir. Dərin iç-içə şərtlər «piramida» yaradır və oxunaqlığı azaldır.' },
      { level: 'senior', q: 'Bu kod nə çap edir?', code: 'fun main() {\n    val s: String? = null\n    if (s != null && s.length > 3) println("uzun")\n    else println("qisa ve ya null")\n}', opts: ['uzun', 'qisa ve ya null', 'NullPointerException', 'Kompilyasiya xətası'], a: 1, exp: 's null olduğu üçün birinci şərt yalandır və qısa qapanma sayəsində s.length heç hesablanmır — NPE riski yoxdur. else budağı işləyir.' }
    ],

    praktiki: [
      { level: 'junior', tapsiriq: 'yas 20-dir. Əgər 18-dən böyük və ya bərabərdirsə "boyuk", əks halda "kicik" çap et.', starter: 'fun main() {\n    val yas = 20\n    \n}', gozlenilen: 'boyuk', ipucu: 'if (yas >= 18) ... else ...', hell: 'fun main() {\n    val yas = 20\n    if (yas >= 18) println("boyuk") else println("kicik")\n}' },
      { level: 'junior', tapsiriq: 'if-i İFADƏ kimi işlədib 12 və 30 ədədlərindən böyüyünü çap et.', starter: 'fun main() {\n    val a = 12\n    val b = 30\n    val maks = // buranı tamamla\n    println(maks)\n}', gozlenilen: '30', ipucu: 'val maks = if (a > b) a else b', hell: 'fun main() {\n    val a = 12\n    val b = 30\n    val maks = if (a > b) a else b\n    println(maks)\n}' },
      { level: 'junior', tapsiriq: 'Ədədin cüt və ya tək olduğunu yoxla: 7 üçün "tek" çap et.', starter: 'fun main() {\n    val n = 7\n    \n}', gozlenilen: 'tek', ipucu: 'n % 2 == 0 şərtini yoxla.', hell: 'fun main() {\n    val n = 7\n    if (n % 2 == 0) println("cut") else println("tek")\n}' },
      { level: 'junior', tapsiriq: 'when ilə reqem = 2 üçün "Iki" çap et. 1, 2, 3 üçün müvafiq adları, qalanlar üçün "Diger" yaz.', starter: 'fun main() {\n    val reqem = 2\n    \n}', gozlenilen: 'Iki', ipucu: 'when (reqem) { 1 -> ...; 2 -> ...; else -> ... }', hell: 'fun main() {\n    val reqem = 2\n    when (reqem) {\n        1 -> println("Bir")\n        2 -> println("Iki")\n        3 -> println("Uc")\n        else -> println("Diger")\n    }\n}' },
      { level: 'junior', tapsiriq: 'when-də bir neçə dəyəri bir budağa yığ: 6 və 7 üçün "istirahet" çap et. gun = 7 olsun.', starter: 'fun main() {\n    val gun = 7\n    \n}', gozlenilen: 'istirahet', ipucu: 'Dəyərləri vergüllə sadala: 6, 7 -> ...', hell: 'fun main() {\n    val gun = 7\n    when (gun) {\n        6, 7 -> println("istirahet")\n        else -> println("is gunu")\n    }\n}' },
      { level: 'junior', tapsiriq: 'İki şərti && ilə birləşdir: yas 25 və aktivdir true olduqda "qebul edildi" çap et.', starter: 'fun main() {\n    val yas = 25\n    val aktivdir = true\n    \n}', gozlenilen: 'qebul edildi', ipucu: 'if (yas >= 18 && aktivdir) ...', hell: 'fun main() {\n    val yas = 25\n    val aktivdir = true\n    if (yas >= 18 && aktivdir) println("qebul edildi")\n}' },
      { level: 'junior', tapsiriq: 'Üç ədəddən ən böyüyünü tap və çap et: 14, 8, 23.', starter: 'fun main() {\n    val a = 14\n    val b = 8\n    val c = 23\n    \n}', gozlenilen: '23', ipucu: 'İç-içə if və ya maxOf(a, b, c) işlət.', hell: 'fun main() {\n    val a = 14\n    val b = 8\n    val c = 23\n    println(maxOf(a, b, c))\n}' },
      { level: 'junior', tapsiriq: '|| operatoru ilə yoxla: reqem 0-dan kiçik VƏ YA 100-dən böyükdürsə "araliqdan kenar" çap et. reqem = 150.', starter: 'fun main() {\n    val reqem = 150\n    \n}', gozlenilen: 'araliqdan kenar', ipucu: 'if (reqem < 0 || reqem > 100) ...', hell: 'fun main() {\n    val reqem = 150\n    if (reqem < 0 || reqem > 100) println("araliqdan kenar")\n}' },
      { level: 'junior', tapsiriq: 'Boolean dəyişəni inkar edib çap et: aktivdir = false olsun, "!aktivdir" nəticəsini göstər.', starter: 'fun main() {\n    val aktivdir = false\n    \n}', gozlenilen: 'true', ipucu: 'println(!aktivdir)', hell: 'fun main() {\n    val aktivdir = false\n    println(!aktivdir)\n}' },
      { level: 'middle', tapsiriq: 'when-də ARALIQ yoxla: bal = 85 üçün 90+ "Ela", 70..89 "Yaxsi", qalanı "Kafi" olsun. Nəticəni çap et.', starter: 'fun main() {\n    val bal = 85\n    val q = when {\n        // budaqlari yaz\n    }\n    println(q)\n}', gozlenilen: 'Yaxsi', ipucu: 'when { bal >= 90 -> "Ela"; bal >= 70 -> "Yaxsi"; else -> "Kafi" }', hell: 'fun main() {\n    val bal = 85\n    val q = when {\n        bal >= 90 -> "Ela"\n        bal >= 70 -> "Yaxsi"\n        else -> "Kafi"\n    }\n    println(q)\n}' },
      { level: 'middle', tapsiriq: 'when + in operatoru: gun = 3 üçün 1..5 aralığında olsa "is gunu" nəticəsini qaytar və çap et.', starter: 'fun main() {\n    val gun = 3\n    val tip = when (gun) {\n        // budaqlari yaz\n    }\n    println(tip)\n}', gozlenilen: 'is gunu', ipucu: 'in 1..5 -> "is gunu"', hell: 'fun main() {\n    val gun = 3\n    val tip = when (gun) {\n        in 1..5 -> "is gunu"\n        in 6..7 -> "istirahet"\n        else -> "yanlis"\n    }\n    println(tip)\n}' },
      { level: 'middle', tapsiriq: 'is ilə tip yoxla: Any tipli dəyişən String saxlayırsa uzunluğunu, Int saxlayırsa özünü çap et. Dəyər "Kotlin" olsun.', starter: 'fun main() {\n    val obyekt: Any = "Kotlin"\n    when (obyekt) {\n        // budaqlari yaz\n    }\n}', gozlenilen: '6', ipucu: 'is String -> println(obyekt.length) — smart cast işləyir.', hell: 'fun main() {\n    val obyekt: Any = "Kotlin"\n    when (obyekt) {\n        is String -> println(obyekt.length)\n        is Int -> println(obyekt)\n        else -> println("namelum")\n    }\n}' },
      { level: 'middle', tapsiriq: 'Tək ifadəli funksiya yaz: qiymet(bal) 50-dən böyük olanda "kecdi", əks halda "kecmedi" qaytarsın. 60 üçün çağır.', starter: 'fun main() {\n    println(qiymet(60))\n}\n\n// funksiyani yaz', gozlenilen: 'kecdi', ipucu: 'fun qiymet(bal: Int) = if (bal > 50) "kecdi" else "kecmedi"', hell: 'fun main() {\n    println(qiymet(60))\n}\n\nfun qiymet(bal: Int) = if (bal > 50) "kecdi" else "kecmedi"' },
      { level: 'middle', tapsiriq: 'Null təhlükəsiz şərt: s null olduqda "bosdur" çap et. Qısa qapanmadan istifadə et.', starter: 'fun main() {\n    val s: String? = null\n    \n}', gozlenilen: 'bosdur', ipucu: 'if (s != null && s.isNotEmpty()) ... else println("bosdur")', hell: 'fun main() {\n    val s: String? = null\n    if (s != null && s.isNotEmpty()) println(s) else println("bosdur")\n}' },
      { level: 'middle', tapsiriq: 'when-in subject-ində dəyişən elan et: hesabla() nəticəsini n dəyişənində saxla və 10-dan böyükdürsə "boyuk" çap et.', starter: 'fun hesabla() = 42\n\nfun main() {\n    when (val n = hesabla()) {\n        // budaqlari yaz\n    }\n}', gozlenilen: 'boyuk', ipucu: 'in Int.MIN_VALUE..10 -> ... ; else -> println("boyuk") — və ya arqumentsiz when.', hell: 'fun hesabla() = 42\n\nfun main() {\n    when (val n = hesabla()) {\n        in Int.MIN_VALUE..10 -> println("kicik")\n        else -> println("boyuk")\n    }\n}' },
      { level: 'middle', tapsiriq: 'Mətn şablonunda if işlət: reqem = -5 üçün "-5 menfidir" çap et.', starter: 'fun main() {\n    val reqem = -5\n    \n}', gozlenilen: '-5 menfidir', ipucu: 'println("$reqem ${if (reqem < 0) "menfidir" else "musbetdir"}")', hell: 'fun main() {\n    val reqem = -5\n    println("$reqem ${if (reqem < 0) "menfidir" else "musbetdir"}")\n}' },
      { level: 'middle', tapsiriq: 'İki şərtli yoxlama yaz: il 2024 həm 4-ə bölünür, həm də 100-ə bölünmür — "uzun il" çap et.', starter: 'fun main() {\n    val il = 2024\n    \n}', gozlenilen: 'uzun il', ipucu: 'if (il % 4 == 0 && il % 100 != 0) ...', hell: 'fun main() {\n    val il = 2024\n    if (il % 4 == 0 && il % 100 != 0) println("uzun il") else println("adi il")\n}' },
      { level: 'middle', tapsiriq: 'enum yarat (AKTIV, PASSIV) və when ilə AKTIV üçün "isleyir" çap et — else YAZMA.', starter: 'enum class Status { AKTIV, PASSIV }\n\nfun main() {\n    val s = Status.AKTIV\n    val netice = when (s) {\n        // budaqlari yaz (else yazma)\n    }\n    println(netice)\n}', gozlenilen: 'isleyir', ipucu: 'Bütün enum sabitlərini sadala — onda else lazım olmur.', hell: 'enum class Status { AKTIV, PASSIV }\n\nfun main() {\n    val s = Status.AKTIV\n    val netice = when (s) {\n        Status.AKTIV -> "isleyir"\n        Status.PASSIV -> "dayanib"\n    }\n    println(netice)\n}' },
      { level: 'middle', tapsiriq: 'İç-içə if işlət: yas 25, ehtiyat 500 — hər ikisi kifayətdirsə "tesdiq" çap et.', starter: 'fun main() {\n    val yas = 25\n    val ehtiyat = 500\n    \n}', gozlenilen: 'tesdiq', ipucu: 'Xarici if yaşı, daxili if ehtiyatı yoxlasın.', hell: 'fun main() {\n    val yas = 25\n    val ehtiyat = 500\n    if (yas >= 18) {\n        if (ehtiyat >= 100) println("tesdiq") else println("ehtiyat azdir")\n    } else {\n        println("yas kicikdir")\n    }\n}' },
      { level: 'senior', tapsiriq: 'sealed class ilə when yaz: Ugurlu("data") halı üçün "Ugurlu: data" çap et. else yazma.', starter: 'sealed class Netice {\n    data class Ugurlu(val data: String) : Netice()\n    data class Xeta(val kod: Int) : Netice()\n}\n\nfun main() {\n    val n: Netice = Netice.Ugurlu("data")\n    val metn = when (n) {\n        // budaqlari yaz\n    }\n    println(metn)\n}', gozlenilen: 'Ugurlu: data', ipucu: 'is Netice.Ugurlu -> "Ugurlu: ${n.data}" — smart cast işləyir.', hell: 'sealed class Netice {\n    data class Ugurlu(val data: String) : Netice()\n    data class Xeta(val kod: Int) : Netice()\n}\n\nfun main() {\n    val n: Netice = Netice.Ugurlu("data")\n    val metn = when (n) {\n        is Netice.Ugurlu -> "Ugurlu: ${n.data}"\n        is Netice.Xeta -> "Xeta: ${n.kod}"\n    }\n    println(metn)\n}' },
      { level: 'senior', tapsiriq: 'Erkən çıxış (early return) yaz: emal(null) çağırışında "bos giris" qaytarılsın və çap edilsin.', starter: 'fun main() {\n    println(emal(null))\n}\n\nfun emal(giris: String?): String {\n    // erkən çıxış yaz\n    return giris.uppercase()\n}', gozlenilen: 'bos giris', ipucu: 'val temiz = giris ?: return "bos giris"', hell: 'fun main() {\n    println(emal(null))\n}\n\nfun emal(giris: String?): String {\n    val temiz = giris ?: return "bos giris"\n    return temiz.uppercase()\n}' },
      { level: 'senior', tapsiriq: 'Kod qoxusunu düzəlt: "if (x > 5) true else false" yerinə birbaşa müqayisə yaz. x = 8 üçün nəticəni çap et.', starter: 'fun main() {\n    val x = 8\n    val netice = // sade formada yaz\n    println(netice)\n}', gozlenilen: 'true', ipucu: 'Müqayisə onsuz da Boolean qaytarır: val netice = x > 5', hell: 'fun main() {\n    val x = 8\n    val netice = x > 5\n    println(netice)\n}' },
      { level: 'senior', tapsiriq: 'when ilə HTTP kodunu emal et: 404 üçün "Tapilmadi", 500..599 üçün "Server xetasi", 200 üçün "OK" qaytar. Kod 503 olsun.', starter: 'fun main() {\n    println(tesvir(503))\n}\n\nfun tesvir(kod: Int): String = when {\n    // budaqlari yaz\n}', gozlenilen: 'Server xetasi', ipucu: 'kod == 200 -> "OK"; kod == 404 -> "Tapilmadi"; kod in 500..599 -> "Server xetasi"; else -> "Namelum"', hell: 'fun main() {\n    println(tesvir(503))\n}\n\nfun tesvir(kod: Int): String = when {\n    kod == 200 -> "OK"\n    kod == 404 -> "Tapilmadi"\n    kod in 500..599 -> "Server xetasi"\n    else -> "Namelum"\n}' },
      { level: 'senior', tapsiriq: '!in operatorunu işlət: reqem 1..10 aralığında DEYİLSƏ "kenar" çap et. reqem = 42.', starter: 'fun main() {\n    val reqem = 42\n    \n}', gozlenilen: 'kenar', ipucu: 'if (reqem !in 1..10) println("kenar")', hell: 'fun main() {\n    val reqem = 42\n    if (reqem !in 1..10) println("kenar") else println("daxil")\n}' },
      { level: 'senior', tapsiriq: 'when budaqlarının ardıcıllığını göstər: bal = 95 üçün BİRİNCİ uyğun budaq işləməlidir. "Ela" çap olunsun.', starter: 'fun main() {\n    val bal = 95\n    val q = when {\n        bal >= 50 -> "Kafi"\n        bal >= 90 -> "Ela"\n        else -> "Zeif"\n    }\n    println(q)\n    // Diqqet: budaqlarin sirasini duzelt ki, "Ela" cixsin\n}', gozlenilen: 'Ela', ipucu: 'Daha spesifik şərt (bal >= 90) yuxarıda yazılmalıdır.', hell: 'fun main() {\n    val bal = 95\n    val q = when {\n        bal >= 90 -> "Ela"\n        bal >= 50 -> "Kafi"\n        else -> "Zeif"\n    }\n    println(q)\n}' }
    ]
  });

  /* ==========================================================
     04 · DÖVRLƏR VƏ ARALIQLAR
     ========================================================== */
  movzu({
    id: 'dovrler',
    title: 'Dövrlər və aralıqlar',
    sectionId: 'dovrler',

    nezeri: [
      { level: 'junior', q: 'Kotlin-də klassik for (i = 0; i < n; i++) forması varmı?', opts: ['Bəli', 'Xeyr — aralıqlar və iterator əsaslı for işlədilir', 'Yalnız massivlərdə', 'Yalnız while ilə'], a: 1, exp: 'Kotlin-də C üslubunda for yoxdur. Onun yerinə for (i in 0 until n) və ya for (element in kolleksiya) formaları işlədilir — daha qısa və səhvsizdir.' },
      { level: 'junior', q: '1..5 aralığı hansı ədədləri əhatə edir?', opts: ['1, 2, 3, 4', '1, 2, 3, 4, 5', '0, 1, 2, 3, 4', '2, 3, 4, 5'], a: 1, exp: '.. operatoru hər iki ucu daxil edir (closed range). Son ədədi çıxarmaq üçün ..< və ya until işlədilir.' },
      { level: 'junior', q: '0..<5 aralığı neçə ədəd verir?', opts: ['4', '5', '6', '0'], a: 1, exp: '0, 1, 2, 3, 4 — yəni 5 ədəd. ..< son ədədi daxil etmir (əvvəllər until adlanırdı).' },
      { level: 'junior', q: 'Azalan aralıq üçün hansı açar söz işlədilir?', opts: ['reverse', 'downTo', 'backTo', 'desc'], a: 1, exp: '10 downTo 1 azalan ardıcıllıq yaradır. Sadəcə 10..1 yazsan aralıq boş olur və dövr heç işləmir.' },
      { level: 'junior', q: 'Addımı dəyişmək üçün hansı açar söz işlədilir?', opts: ['by', 'step', 'skip', 'jump'], a: 1, exp: '1..10 step 2 → 1, 3, 5, 7, 9. step həmişə müsbət olmalıdır; azalma üçün downTo ilə birlikdə işlədilir.' },
      { level: 'junior', q: 'while və do-while arasındakı fərq nədir?', opts: ['Fərq yoxdur', 'do-while gövdəni ən azı bir dəfə işlədir', 'while daha sürətlidir', 'do-while yalnız Java-da var'], a: 1, exp: 'while şərti əvvəldə yoxlayır — şərt yalandırsa gövdə heç işləmir. do-while isə gövdəni işlədib sonra şərti yoxlayır, ona görə ən azı bir dəfə icra olunur.' },
      { level: 'junior', q: 'break nə edir?', opts: ['Cari addımı atlayır', 'Dövrü tamamilə dayandırır', 'Funksiyadan çıxır', 'Xəta atır'], a: 1, exp: 'break dövrü dərhal dayandırır və icra dövrdən sonrakı sətirdən davam edir. Yalnız cari addımı atlamaq üçün continue işlədilir.' },
      { level: 'junior', q: 'continue nə edir?', opts: ['Dövrü dayandırır', 'Cari addımı atlayıb növbətiyə keçir', 'Dövrü yenidən başladır', 'Proqramı bitirir'], a: 1, exp: 'continue qalan gövdəni atlayır və növbəti iterasiyaya keçir. Dövr davam edir.' },
      { level: 'junior', q: 'Bu kod nə çap edir?', code: 'fun main() {\n    for (i in 1..3) print("$i ")\n}', opts: ['1 2 3', '1 2', '0 1 2', '1 2 3 4'], a: 0, exp: '1..3 aralığı hər iki ucu daxil edir: 1, 2, 3. print() sətri dəyişmədiyi üçün hamısı bir sətirdə çıxır.' },
      { level: 'middle', q: 'Kolleksiyanı indeksi ilə birlikdə gəzmək üçün nə işlədilir?', opts: ['withIndex()', 'indexed()', 'enumerate()', 'pairs()'], a: 0, exp: 'for ((index, deyer) in siyahi.withIndex()) formasında həm indeks, həm dəyər alınır. Yalnız indekslər lazımdırsa siyahi.indices işlədilir.' },
      { level: 'middle', q: 'repeat(3) { ... } nə edir?', opts: ['Bloku 3 dəfə işlədir', 'Siyahını 3 dəfə təkrarlayır', '3 saniyə gözləyir', '3 ədəd qaytarır'], a: 0, exp: 'repeat() standart kitabxananın inline funksiyasıdır. Sadəcə bloku n dəfə işlədir və iterasiya indeksini lambda parametri kimi verir.' },
      { level: 'middle', q: 'Bu kodun nəticəsi nədir?', code: 'fun main() {\n    for (i in 10 downTo 1 step 3) print("$i ")\n}', opts: ['10 7 4 1', '1 4 7 10', '10 9 8 7', '10 7 4'], a: 0, exp: '10-dan başlayıb hər dəfə 3 azalır: 10, 7, 4, 1. Növbəti dəyər (−2) aralıqdan kənarda qalır.' },
      { level: 'middle', q: 'Map üzərində for necə yazılır?', opts: ['for (m in map)', 'for ((acar, deyer) in map)', 'for (map.each)', 'Mümkün deyil'], a: 1, exp: 'Map-in elementləri Entry-dir və destrukturizasiyanı dəstəkləyir, ona görə for ((acar, deyer) in map) yazmaq olar.' },
      { level: 'middle', q: 'forEach daxilində sadə return nə edir?', code: 'listOf(1,2,3).forEach {\n    if (it == 2) return\n    println(it)\n}', opts: ['Yalnız cari addımı atlayır', 'BÜTÜN funksiyadan çıxır', 'Dövrü yenidən başladır', 'Kompilyasiya xətası'], a: 1, exp: 'forEach inline olduğu üçün return xarici funksiyadan çıxır (non-local return). Yalnız addımı atlamaq üçün return@forEach yazmaq lazımdır.' },
      { level: 'middle', q: 'İç-içə dövrlərdən birdəfəyə çıxmaq üçün nə işlədilir?', opts: ['break break', 'Etiket (label): break@xarici', 'exit()', 'goto'], a: 1, exp: 'Dövrə etiket verilir (xarici@ for ...) və break@xarici yazılır. Etiketsiz break yalnız ən daxili dövrdən çıxır.' },
      { level: 'middle', q: '(1..10).sum() nə qaytarır?', opts: ['10', '55', '45', '11'], a: 1, exp: '1-dən 10-a qədər ədədlərin cəmi: 10 × 11 / 2 = 55. Aralıqlar kolleksiya funksiyalarını dəstəkləyir.' },
      { level: 'middle', q: 'Bu kod neçə dəfə işləyir?', code: 'var n = 0\nwhile (n > 5) {\n    n++\n}', opts: ['5 dəfə', '6 dəfə', 'Heç bir dəfə', 'Sonsuz'], a: 2, exp: 'Şərt əvvəldə yoxlanılır: 0 > 5 yalandır, ona görə gövdə heç işləmir. do-while olsaydı bir dəfə işləyərdi.' },
      { level: 'middle', q: 'Char aralığı yazmaq olarmı?', code: "for (c in 'a'..'e') print(c)", opts: ['Xeyr', 'Bəli — abcde çap edir', 'Yalnız rəqəmlərlə', 'Kompilyasiya xətası'], a: 1, exp: 'Char da Comparable olduğu üçün aralıq yaradıla bilər. Unicode kodları ardıcıl olan simvollar üzərində gəzir.' },
      { level: 'senior', q: 'Aralıq (IntRange) obyekt yaradırmı, yoxsa optimallaşdırılır?', opts: ['Həmişə obyekt yaradır', 'for dövründə kompilyator onu adi sayğaca çevirir — obyekt yaranmır', 'Heç vaxt işləmir', 'Yalnız Long üçün optimallaşır'], a: 1, exp: 'for (i in 1..n) konstruksiyasında kompilyator IntRange obyekti yaratmır, adi indeksli dövrə çevirir. Amma aralığı dəyişəndə saxlasan obyekt yaranır.' },
      { level: 'senior', q: 'return@forEach nə edir?', opts: ['Funksiyadan çıxır', 'Yalnız cari lambda çağırışından çıxır — continue kimi işləyir', 'Dövrü dayandırır', 'Xəta atır'], a: 1, exp: 'Etiketli return yalnız lambda-dan çıxır, yəni həmin addımı atlayır. Xarici funksiya işləməyə davam edir.' },
      { level: 'senior', q: 'Bu kod nə çap edir?', code: 'fun main() {\n    xarici@ for (i in 1..3) {\n        for (j in 1..3) {\n            if (j == 2) continue@xarici\n            print("$i$j ")\n        }\n    }\n}', opts: ['11 21 31', '11 12 13', '11 21', '12 22 32'], a: 0, exp: 'Hər xarici addımda j=1 çap olunur, j=2 olanda continue@xarici daxili dövrü tərk edib növbəti i-yə keçir. Nəticə: 11, 21, 31.' },
      { level: 'senior', q: 'Sonsuz dövr yazmağın idiomatik yolu nədir?', opts: ['for (;;)', 'while (true)', 'loop { }', 'repeat(Int.MAX_VALUE)'], a: 1, exp: 'while (true) ən aydın formadır. Kotlin-də for (;;) sintaksisi yoxdur. Belə dövrlər mütləq break və ya return ilə tərk edilməlidir.' },
      { level: 'senior', q: 'Böyük kolleksiyada zəncirli əməliyyatlar üçün nə tövsiyə olunur?', opts: ['Adi List əməliyyatları', 'asSequence() — aralıq siyahılar yaranmır', 'İç-içə for dövrləri', 'Fərq yoxdur'], a: 1, exp: 'Adi zəncirdə hər addım yeni siyahı yaradır. Sequence elementləri bir-bir emal edir və aralıq kolleksiya yaratmır — böyük məlumatda xeyli qənaət verir.' },
      { level: 'senior', q: 'indices xassəsi nə qaytarır?', opts: ['Elementləri', 'Etibarlı indekslərin aralığını (0..size-1)', 'Elementlərin sayını', 'Son indeksi'], a: 1, exp: 'siyahi.indices → IntRange. for (i in siyahi.indices) formasında indekslərlə gəzmək üçün işlədilir. Son indeks üçün lastIndex var.' },
      { level: 'senior', q: 'Bu dövr neçə element çap edir?', code: 'fun main() {\n    val s = listOf(1, 2, 3, 4, 5)\n    for (i in s.indices step 2) print(s[i])\n}', opts: ['2', '3', '5', '4'], a: 1, exp: 'indices → 0..4, step 2 ilə 0, 2, 4 indeksləri seçilir — yəni 3 element (1, 3, 5) çap olunur.' }
    ],

    praktiki: [
      { level: 'junior', tapsiriq: '1-dən 5-ə qədər ədədləri bir sətirdə, aralarında boşluqla çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '1 2 3 4 5', ipucu: 'for (i in 1..5) print("$i ")', hell: 'fun main() {\n    for (i in 1..5) print("$i ")\n    println()\n}' },
      { level: 'junior', tapsiriq: '0-dan 4-ə qədər (5 daxil deyil) ədədləri bir sətirdə çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '0 1 2 3 4', ipucu: '0..<5 aralığından istifadə et.', hell: 'fun main() {\n    for (i in 0..<5) print("$i ")\n    println()\n}' },
      { level: 'junior', tapsiriq: '5-dən 1-ə qədər azalan sırada çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '5 4 3 2 1', ipucu: 'downTo açar sözündən istifadə et.', hell: 'fun main() {\n    for (i in 5 downTo 1) print("$i ")\n    println()\n}' },
      { level: 'junior', tapsiriq: '1-dən 10-a qədər ədədləri 2 addımla çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '1 3 5 7 9', ipucu: 'step 2 əlavə et.', hell: 'fun main() {\n    for (i in 1..10 step 2) print("$i ")\n    println()\n}' },
      { level: 'junior', tapsiriq: 'Siyahını gəzib hər elementi ayrı sətirdə çap et: "Kotlin", "Java", "Swift".', starter: 'fun main() {\n    val diller = listOf("Kotlin", "Java", "Swift")\n    \n}', gozlenilen: 'Kotlin\nJava\nSwift', ipucu: 'for (dil in diller) println(dil)', hell: 'fun main() {\n    val diller = listOf("Kotlin", "Java", "Swift")\n    for (dil in diller) println(dil)\n}' },
      { level: 'junior', tapsiriq: 'while dövrü ilə 3-dən 1-ə qədər say və bir sətirdə çap et.', starter: 'fun main() {\n    var n = 3\n    \n}', gozlenilen: '3 2 1', ipucu: 'while (n > 0) { print("$n "); n-- }', hell: 'fun main() {\n    var n = 3\n    while (n > 0) {\n        print("$n ")\n        n--\n    }\n    println()\n}' },
      { level: 'junior', tapsiriq: 'repeat() işlədib "Salam" mətnini 3 dəfə ayrı sətirlərdə çap et.', starter: 'fun main() {\n    \n}', gozlenilen: 'Salam\nSalam\nSalam', ipucu: 'repeat(3) { println("Salam") }', hell: 'fun main() {\n    repeat(3) {\n        println("Salam")\n    }\n}' },
      { level: 'junior', tapsiriq: "'a'-dan 'e'-yə qədər simvolları bitişik çap et.", starter: 'fun main() {\n    \n}', gozlenilen: 'abcde', ipucu: "for (c in 'a'..'e') print(c)", hell: "fun main() {\n    for (c in 'a'..'e') print(c)\n    println()\n}" },
      { level: 'junior', tapsiriq: '1-dən 10-a qədər ədədlərin cəmini hesablayıb çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '55', ipucu: '(1..10).sum() və ya dövrlə topla.', hell: 'fun main() {\n    println((1..10).sum())\n}' },
      { level: 'middle', tapsiriq: 'withIndex() ilə siyahını nömrələ: "1. Kotlin", "2. Java" formasında çap et.', starter: 'fun main() {\n    val diller = listOf("Kotlin", "Java")\n    \n}', gozlenilen: '1. Kotlin\n2. Java', ipucu: 'for ((i, dil) in diller.withIndex()) println("${i + 1}. $dil")', hell: 'fun main() {\n    val diller = listOf("Kotlin", "Java")\n    for ((i, dil) in diller.withIndex()) {\n        println("${i + 1}. $dil")\n    }\n}' },
      { level: 'middle', tapsiriq: 'break işlət: 1-dən 10-a qədər gəz, 4-ə çatanda dayan. Çap olunanlar bir sətirdə olsun.', starter: 'fun main() {\n    \n}', gozlenilen: '1 2 3', ipucu: 'if (i == 4) break', hell: 'fun main() {\n    for (i in 1..10) {\n        if (i == 4) break\n        print("$i ")\n    }\n    println()\n}' },
      { level: 'middle', tapsiriq: 'continue işlət: 1-dən 6-ya qədər yalnız TƏK ədədləri bir sətirdə çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '1 3 5', ipucu: 'if (i % 2 == 0) continue', hell: 'fun main() {\n    for (i in 1..6) {\n        if (i % 2 == 0) continue\n        print("$i ")\n    }\n    println()\n}' },
      { level: 'middle', tapsiriq: 'do-while işlət: sayqac 0-dan başlasın, 3-ə çatana qədər hər dəfə artırıb "Sayqac: N" çap et.', starter: 'fun main() {\n    var sayqac = 0\n    \n}', gozlenilen: 'Sayqac: 1\nSayqac: 2\nSayqac: 3', ipucu: 'do { sayqac++; println("Sayqac: $sayqac") } while (sayqac < 3)', hell: 'fun main() {\n    var sayqac = 0\n    do {\n        sayqac++\n        println("Sayqac: $sayqac")\n    } while (sayqac < 3)\n}' },
      { level: 'middle', tapsiriq: 'Map üzərində gəz və "acar -> deyer" formasında çap et. Map: ad=Aysel, yas=24.', starter: 'fun main() {\n    val m = linkedMapOf("ad" to "Aysel", "yas" to "24")\n    \n}', gozlenilen: 'ad -> Aysel\nyas -> 24', ipucu: 'for ((acar, deyer) in m) println("$acar -> $deyer")', hell: 'fun main() {\n    val m = linkedMapOf("ad" to "Aysel", "yas" to "24")\n    for ((acar, deyer) in m) {\n        println("$acar -> $deyer")\n    }\n}' },
      { level: 'middle', tapsiriq: 'indices ilə gəz: siyahının indekslərini və elementlərini "0:a" formasında bir sətirdə çap et.', starter: 'fun main() {\n    val s = listOf("a", "b", "c")\n    \n}', gozlenilen: '0:a 1:b 2:c', ipucu: 'for (i in s.indices) print("$i:${s[i]} ")', hell: 'fun main() {\n    val s = listOf("a", "b", "c")\n    for (i in s.indices) print("$i:${s[i]} ")\n    println()\n}' },
      { level: 'middle', tapsiriq: 'Vurma cədvəlinin bir sətrini yaz: 3-ün 1..5 ilə hasillərini bir sətirdə çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '3 6 9 12 15', ipucu: 'for (i in 1..5) print("${3 * i} ")', hell: 'fun main() {\n    for (i in 1..5) print("${3 * i} ")\n    println()\n}' },
      { level: 'middle', tapsiriq: 'Dövrlə faktorial hesabla: 5! nəticəsini çap et.', starter: 'fun main() {\n    var netice = 1\n    \n}', gozlenilen: '120', ipucu: 'for (i in 1..5) netice *= i', hell: 'fun main() {\n    var netice = 1\n    for (i in 1..5) netice *= i\n    println(netice)\n}' },
      { level: 'middle', tapsiriq: 'İç-içə dövr yaz: 1..2 və 1..2 üçün cütləri "11 12 21 22" formasında bir sətirdə çap et.', starter: 'fun main() {\n    \n}', gozlenilen: '11 12 21 22', ipucu: 'İki for-u iç-içə yaz və print("$i$j ") işlət.', hell: 'fun main() {\n    for (i in 1..2) {\n        for (j in 1..2) {\n            print("$i$j ")\n        }\n    }\n    println()\n}' },
      { level: 'middle', tapsiriq: 'Siyahıda ədədlərin cəmini dövrlə hesablayıb çap et: 4, 8, 15, 16.', starter: 'fun main() {\n    val s = listOf(4, 8, 15, 16)\n    var cem = 0\n    \n}', gozlenilen: '43', ipucu: 'for (x in s) cem += x', hell: 'fun main() {\n    val s = listOf(4, 8, 15, 16)\n    var cem = 0\n    for (x in s) cem += x\n    println(cem)\n}' },
      { level: 'senior', tapsiriq: 'Etiket işlət: iç-içə dövrdə i*j == 4 olanda HƏR İKİ dövrdən çıx və "Tapildi" çap et.', starter: 'fun main() {\n    // etiketli dovru yaz\n}', gozlenilen: 'Tapildi', ipucu: 'xarici@ for (...) { for (...) { if (...) { println("Tapildi"); break@xarici } } }', hell: 'fun main() {\n    xarici@ for (i in 1..3) {\n        for (j in 1..3) {\n            if (i * j == 4) {\n                println("Tapildi")\n                break@xarici\n            }\n        }\n    }\n}' },
      { level: 'senior', tapsiriq: 'return@forEach işlət: 1..5 siyahısında 3-ü atla, qalanlarını bir sətirdə çap et.', starter: 'fun main() {\n    listOf(1, 2, 3, 4, 5).forEach {\n        // burani tamamla\n    }\n    println()\n}', gozlenilen: '1 2 4 5', ipucu: 'if (it == 3) return@forEach — sadə return bütün funksiyadan çıxardı.', hell: 'fun main() {\n    listOf(1, 2, 3, 4, 5).forEach {\n        if (it == 3) return@forEach\n        print("$it ")\n    }\n    println()\n}' },
      { level: 'senior', tapsiriq: 'continue@etiket işlət: i*j-lərdən yalnız j==1 olanları "11 21 31" formasında çap et.', starter: 'fun main() {\n    // etiketli continue isle\n    println()\n}', gozlenilen: '11 21 31', ipucu: 'j == 2 olanda continue@xarici yaz.', hell: 'fun main() {\n    xarici@ for (i in 1..3) {\n        for (j in 1..3) {\n            if (j == 2) continue@xarici\n            print("$i$j ")\n        }\n    }\n    println()\n}' },
      { level: 'senior', tapsiriq: 'while (true) və break işlət: sayğac 3-ə çatanda dayan və son dəyəri çap et.', starter: 'fun main() {\n    var n = 0\n    \n}', gozlenilen: '3', ipucu: 'while (true) { n++; if (n == 3) break }', hell: 'fun main() {\n    var n = 0\n    while (true) {\n        n++\n        if (n == 3) break\n    }\n    println(n)\n}' },
      { level: 'senior', tapsiriq: 'Fibonaççi ardıcıllığının ilk 7 üzvünü bir sətirdə çap et (1-dən başla).', starter: 'fun main() {\n    var a = 1\n    var b = 1\n    \n}', gozlenilen: '1 1 2 3 5 8 13', ipucu: 'İki dəyişəni yerlərini dəyişərək dövrdə irəlilət.', hell: 'fun main() {\n    var a = 1\n    var b = 1\n    repeat(7) {\n        print("$a ")\n        val n = a + b\n        a = b\n        b = n\n    }\n    println()\n}' },
      { level: 'senior', tapsiriq: 'indices step 2 işlət: siyahının cüt indeksli elementlərini bitişik çap et.', starter: 'fun main() {\n    val s = listOf(1, 2, 3, 4, 5)\n    \n}', gozlenilen: '135', ipucu: 'for (i in s.indices step 2) print(s[i])', hell: 'fun main() {\n    val s = listOf(1, 2, 3, 4, 5)\n    for (i in s.indices step 2) print(s[i])\n    println()\n}' }
    ]
  });

  /* [[NOVBETI-MOVZU-BURA]] */

  window.KExercises = BANK;
})();
